CREATE DATABASE Actividad_1_4
GO
USE Actividad_1_4
GO
CREATE TABLE TipoClientes(
  ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  Descripcion VARCHAR(50) NOT NULL UNIQUE
)

GO
CREATE TABLE Paises(
  ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  ISO VARCHAR(2) NOT NULL,
  Descripcion VARCHAR(100) NOT NULL
)

GO
CREATE TABLE Provincias(
  ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  IDPais INT NOT NULL FOREIGN KEY REFERENCES Paises(ID),
  Descripcion VARCHAR(50) NOT NULL
)
GO
CREATE TABLE Localidades(
  ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  IDProvincia INT NOT NULL FOREIGN KEY REFERENCES Provincias(ID),
  Descripcion VARCHAR(100) NOT NULL
)

GO
CREATE TABLE Clientes(
  ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  RazonSocial VARCHAR(50) NOT NULL UNIQUE,
  IDTipoCliente INT NOT NULL FOREIGN KEY REFERENCES TipoClientes(ID),
  Cuit VARCHAR(12) NOT NULL UNIQUE,
  Email VARCHAR(100) NULL,
  TelefonoFijo VARCHAR(20) NULL,
  TelefonoMovil VARCHAR(20) NULL,
  IDLocalidad INT NULL FOREIGN KEY REFERENCES Localidades(ID)    
)

GO
CREATE TABLE Proyectos(
  ID VARCHAR(5) NOT NULL PRIMARY KEY,
  Nombre VARCHAR(100) NOT NULL,
  Descripcion VARCHAR(512) NULL,
  Costo MONEY NOT NULL CHECK (Costo > 0),
  FechaInicio DATE NOT NULL,
  FechaFin DATE NULL,
  IDCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(ID),
  Estado BIT NOT NULL DEFAULT (1)
)

GO
CREATE TABLE Modulos(
  ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  IDProyecto VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES Proyectos(ID),
  Nombre VARCHAR(100) NOT NULL,
  Descripcion VARCHAR(512) NULL,
  TiempoEstimado INT NOT NULL CHECK (TiempoEstimado > 0),
  CostoEstimado MONEY NOT NULL CHECK (CostoEstimado > 0),
  FechaFinEstimada DATE NULL,
  FechaRealInicio DATE NULL,
  FechaRealFin DATE NULL  
)

GO
CREATE TABLE Colaboradores(
  ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  Apellidos VARCHAR(50) NOT NULL,
  Nombres VARCHAR(50) NOT NULL,
  Sexo CHAR(1) NULL CHECK(Sexo = 'F' OR Sexo = 'M'),
  Email VARCHAR(100) NULL,
  TelefonoMovil VARCHAR(20) NULL,
  CHECK (Email != NULL OR TelefonoMovil != NULL),
  FechaNacimiento DATE NOT NULL CHECK(FechaNacimiento < GETDATE()),
  Direccion VARCHAR(100) NULL,
  IDLocalidad INT NULL FOREIGN KEY REFERENCES Localidades(ID),
  TipoColaborador CHAR(1) NULL CHECK(TipoColaborador = 'I' OR TipoColaborador = 'E')
)

GO
INSERT INTO Paises (ISO, Descripcion) VALUES 
	('AF','Afganistán'),
	('AX','Islas Gland'),
	('AL','Albania'),
	('DE','Alemania'),
	('AD','Andorra'),
	('AO','Angola'),
	('AI','Anguilla'),
	('AQ','Antártida'),
	('AG','Antigua y Barbuda'),
	('AN','Antillas Holandesas'),
	('SA','Arabia Saudí'),
	('DZ','Argelia'),
	('AR','Argentina'),
	('AM','Armenia'),
	('AW','Aruba'),
	('AU','Australia'),
	('AT','Austria'),
	('AZ','Azerbaiyán'),
	('BS','Bahamas'),
	('BH','Bahréin'),
	('BD','Bangladesh'),
	('BB','Barbados'),
	('BY','Bielorrusia'),
	('BE','Bélgica'),
	('BZ','Belice'),
	('BJ','Benin'),
	('BM','Bermudas'),
	('BT','Bhután'),
	('BO','Bolivia'),
	('BA','Bosnia y Herzegovina'),
	('BW','Botsuana'),
	('BV','Isla Bouvet'),
	('BR','Brasil'),
	('BN','Brunéi'),
	('BG','Bulgaria'),
	('BF','Burkina Faso'),
	('BI','Burundi'),
	('CV','Cabo Verde'),
	('KY','Islas Caimán'),
	('KH','Camboya'),
	('CM','Camerún'),
	('CA','Canadá'),
	('CF','República Centroafricana'),
	('TD','Chad'),
	('CZ','República Checa'),
	('CL','Chile'),
	('CN','China'),
	('CY','Chipre'),
	('CX','Isla de Navidad'),
	('VA','Ciudad del Vaticano'),
	('CC','Islas Cocos'),
	('CO','Colombia'),
	('KM','Comoras'),
	('CD','República Democrática del Congo'),
	('CG','Congo'),
	('CK','Islas Cook'),
	('KP','Corea del Norte'),
	('KR','Corea del Sur'),
	('CI','Costa de Marfil'),
	('CR','Costa Rica'),
	('HR','Croacia'),
	('CU','Cuba'),
	('DK','Dinamarca'),
	('DM','Dominica'),
	('DO','República Dominicana'),
	('EC','Ecuador'),
	('EG','Egipto'),
	('SV','El Salvador'),
	('AE','Emiratos Árabes Unidos'),
	('ER','Eritrea'),
	('SK','Eslovaquia'),
	('SI','Eslovenia'),
	('ES','España'),
	('UM','Islas ultramarinas de Estados Unidos'),
	('US','Estados Unidos'),
	('EE','Estonia'),
	('ET','Etiopía'),
	('FO','Islas Feroe'),
	('PH','Filipinas'),
	('FI','Finlandia'),
	('FJ','Fiyi'),
	('FR','Francia'),
	('GA','Gabón'),
	('GM','Gambia'),
	('GE','Georgia'),
	('GS','Islas Georgias del Sur y Sandwich del Sur'),
	('GH','Ghana'),
	('GI','Gibraltar'),
	('GD','Granada'),
	('GR','Grecia'),
	('GL','Groenlandia'),
	('GP','Guadalupe'),
	('GU','Guam'),
	('GT','Guatemala'),
	('GF','Guayana Francesa'),
	('GN','Guinea'),
	('GQ','Guinea Ecuatorial'),
	('GW','Guinea-Bissau'),
	('GY','Guyana'),
	('HT','Haití'),
	('HM','Islas Heard y McDonald'),
	('HN','Honduras'),
	('HK','Hong Kong'),
	('HU','Hungría'),
	('IN','India'),
	('ID','Indonesia'),
	('IR','Irán'),
	('IQ','Iraq'),
	('IE','Irlanda'),
	('IS','Islandia'),
	('IL','Israel'),
	('IT','Italia'),
	('JM','Jamaica'),
	('JP','Japón'),
	('JO','Jordania'),
	('KZ','Kazajstán'),
	('KE','Kenia'),
	('KG','Kirguistán'),
	('KI','Kiribati'),
	('KW','Kuwait'),
	('LA','Laos'),
	('LS','Lesotho'),
	('LV','Letonia'),
	('LB','Líbano'),
	('LR','Liberia'),
	('LY','Libia'),
	('LI','Liechtenstein'),
	('LT','Lituania'),
	('LU','Luxemburgo'),
	('MO','Macao'),
	('MK','ARY Macedonia'),
	('MG','Madagascar'),
	('MY','Malasia'),
	('MW','Malawi'),
	('MV','Maldivas'),
	('ML','Malí'),
	('MT','Malta'),
	('FK','Islas Malvinas'),
	('MP','Islas Marianas del Norte'),
	('MA','Marruecos'),
	('MH','Islas Marshall'),
	('MQ','Martinica'),
	('MU','Mauricio'),
	('MR','Mauritania'),
	('YT','Mayotte'),
	('MX','México'),
	('FM','Micronesia'),
	('MD','Moldavia'),
	('MC','Mónaco'),
	('MN','Mongolia'),
	('MS','Montserrat'),
	('MZ','Mozambique'),
	('MM','Myanmar'),
	('NA','Namibia'),
	('NR','Nauru'),
	('NP','Nepal'),
	('NI','Nicaragua'),
	('NE','Níger'),
	('NG','Nigeria'),
	('NU','Niue'),
	('NF','Isla Norfolk'),
	('NO','Noruega'),
	('NC','Nueva Caledonia'),
	('NZ','Nueva Zelanda'),
	('OM','Omán'),
	('NL','Países Bajos'),
	('PK','Pakistán'),
	('PW','Palau'),
	('PS','Palestina'),
	('PA','Panamá'),
	('PG','Papúa Nueva Guinea'),
	('PY','Paraguay'),
	('PE','Perú'),
	('PN','Islas Pitcairn'),
	('PF','Polinesia Francesa'),
	('PL','Polonia'),
	('PT','Portugal'),
	('PR','Puerto Rico'),
	('QA','Qatar'),
	('GB','Reino Unido'),
	('RE','Reunión'),
	('RW','Ruanda'),
	('RO','Rumania'),
	('RU','Rusia'),
	('EH','Sahara Occidental'),
	('SB','Islas Salomón'),
	('WS','Samoa'),
	('AS','Samoa Americana'),
	('KN','San Cristóbal y Nevis'),
	('SM','San Marino'),
	('PM','San Pedro y Miquelón'),
	('VC','San Vicente y las Granadinas'),
	('SH','Santa Helena'),
	('LC','Santa Lucía'),
	('ST','Santo Tomé y Príncipe'),
	('SN','Senegal'),
	('CS','Serbia y Montenegro'),
	('SC','Seychelles'),
	('SL','Sierra Leona'),
	('SG','Singapur'),
	('SY','Siria'),
	('SO','Somalia'),
	('LK','Sri Lanka'),
	('SZ','Suazilandia'),
	('ZA','Sudáfrica'),
	('SD','Sudán'),
	('SE','Suecia'),
	('CH','Suiza'),
	('SR','Surinam'),
	('SJ','Svalbard y Jan Mayen'),
	('TH','Tailandia'),
	('TW','Taiwán'),
	('TZ','Tanzania'),
	('TJ','Tayikistán'),
	('IO','Territorio Británico del Océano Índico'),
	('TF','Territorios Australes Franceses'),
	('TL','Timor Oriental'),
	('TG','Togo'),
	('TK','Tokelau'),
	('TO','Tonga'),
	('TT','Trinidad y Tobago'),
	('TN','Túnez'),
	('TC','Islas Turcas y Caicos'),
	('TM','Turkmenistán'),
	('TR','Turquía'),
	('TV','Tuvalu'),
	('UA','Ucrania'),
	('UG','Uganda'),
	('UY','Uruguay'),
	('UZ','Uzbekistán'),
	('VU','Vanuatu'),
	('VE','Venezuela'),
	('VN','Vietnam'),
	('VG','Islas Vírgenes Británicas'),
	('VI','Islas Vírgenes de los Estados Unidos'),
	('WF','Wallis y Futuna'),
	('YE','Yemen'),
	('DJ','Yibuti'),
	('ZM','Zambia'),
	('ZW','Zimbabue')
	
INSERT INTO Provincias (IDPais, Descripcion) VALUES
	(13, 'Buenos Aires'),
	(13, 'Buenos Aires-GBA'),
	(13, 'Capital Federal'),
	(13, 'Catamarca'),
	(13, 'Chaco'),
	(13, 'Chubut'),
	(13, 'Córdoba'),
	(13, 'Corrientes'),
	(13, 'Entre Ríos'),
	(13, 'Formosa'),
	(13, 'Jujuy'),
	(13, 'La Pampa'),
	(13, 'La Rioja'),
	(13, 'Mendoza'),
	(13, 'Misiones'),
	(13, 'Neuquén'),
	(13, 'Río Negro'),
	(13, 'Salta'),
	(13, 'San Juan'),
	(13, 'San Luis'),
	(13, 'Santa Cruz'),
	(13, 'Santa Fe'),
	(13, 'Santiago del Estero'),
	(13, 'Tierra del Fuego'),
	(13, 'Tucumán'),
	(75, 'Massachusetts'),
	(75, 'Texas'),
	(75, 'Illinois'),
	(180, 'Yorkshire and Humber'),
	(112, 'Toscana'),
	(112, 'Sicilia'),
	(112, 'Roma'),
	(229, 'Montevideo'),	
	(75, 'Michigan'),
	(75, 'Washington'),
	(180, 'Berkshire'),
	(112, 'Campania')


INSERT INTO Localidades (IDProvincia, Descripcion) VALUES	
	(1, '25 de Mayo'),
	(1, '3 de febrero'),
	(1, 'A. Alsina'),
	(1, 'A. Gonzáles Cháves'),
	(1, 'Aguas Verdes'),
	(1, 'Alberti'),
	(1, 'Arrecifes'),
	(1, 'Ayacucho'),
	(1, 'Azul'),
	(1, 'Bahía Blanca'),
	(1, 'Balcarce'),
	(1, 'Baradero'),
	(1, 'Benito Juárez'),
	(1, 'Berisso'),
	(1, 'Bolívar'),
	(1, 'Bragado'),
	(1, 'Brandsen'),
	(1, 'Campana'),
	(1, 'Cañuelas'),
	(1, 'Capilla del Señor'),
	(1, 'Capitán Sarmiento'),
	(1, 'Carapachay'),
	(1, 'Carhue'),
	(1, 'Cariló'),
	(1, 'Carlos Casares'),
	(1, 'Carlos Tejedor'),
	(1, 'Carmen de Areco'),
	(1, 'Carmen de Patagones'),
	(1, 'Castelli'),
	(1, 'Chacabuco'),
	(1, 'Chascomús'),
	(1, 'Chivilcoy'),
	(1, 'Colón'),
	(1, 'Coronel Dorrego'),
	(1, 'Coronel Pringles'),
	(1, 'Coronel Rosales'),
	(1, 'Coronel Suarez'),
	(1, 'Costa Azul'),
	(1, 'Costa Chica'),
	(1, 'Costa del Este'),
	(1, 'Costa Esmeralda'),
	(1, 'Daireaux'),
	(1, 'Darregueira'),
	(1, 'Del Viso'),
	(1, 'Dolores'),
	(1, 'Don Torcuato'),
	(1, 'Ensenada'),
	(1, 'Escobar'),
	(1, 'Exaltación de la Cruz'),
	(1, 'Florentino Ameghino'),
	(1, 'Garín'),
	(1, 'Gral. Alvarado'),
	(1, 'Gral. Alvear'),
	(1, 'Gral. Arenales'),
	(1, 'Gral. Belgrano'),
	(1, 'Gral. Guido'),
	(1, 'Gral. Lamadrid'),
	(1, 'Gral. Las Heras'),
	(1, 'Gral. Lavalle'),
	(1, 'Gral. Madariaga'),
	(1, 'Gral. Pacheco'),
	(1, 'Gral. Paz'),
	(1, 'Gral. Pinto'),
	(1, 'Gral. Pueyrredón'),
	(1, 'Gral. Rodríguez'),
	(1, 'Gral. Viamonte'),
	(1, 'Gral. Villegas'),
	(1, 'Guaminí'),
	(1, 'Guernica'),
	(1, 'Hipólito Yrigoyen'),
	(1, 'Ing. Maschwitz'),
	(1, 'Junín'),
	(1, 'La Plata'),
	(1, 'Laprida'),
	(1, 'Las Flores'),
	(1, 'Las Toninas'),
	(1, 'Leandro N. Alem'),
	(1, 'Lincoln'),
	(1, 'Loberia'),
	(1, 'Lobos'),
	(1, 'Los Cardales'),
	(1, 'Los Toldos'),
	(1, 'Lucila del Mar'),
	(1, 'Luján'),
	(1, 'Magdalena'),
	(1, 'Maipú'),
	(1, 'Mar Chiquita'),
	(1, 'Mar de Ajó'),
	(1, 'Mar de las Pampas'),
	(1, 'Mar del Plata'),
	(1, 'Mar del Tuyú'),
	(1, 'Marcos Paz'),
	(1, 'Mercedes'),
	(1, 'Miramar'),
	(1, 'Monte'),
	(1, 'Monte Hermoso'),
	(1, 'Munro'),
	(1, 'Navarro'),
	(1, 'Necochea'),
	(1, 'Olavarría'),
	(1, 'Partido de la Costa'),
	(1, 'Pehuajó'),
	(1, 'Pellegrini'),
	(1, 'Pergamino'),
	(1, 'Pigüé'),
	(1, 'Pila'),
	(1, 'Pilar'),
	(1, 'Pinamar'),
	(1, 'Pinar del Sol'),
	(1, 'Polvorines'),
	(1, 'Pte. Perón'),
	(1, 'Puán'),
	(1, 'Punta Indio'),
	(1, 'Ramallo'),
	(1, 'Rauch'),
	(1, 'Rivadavia'),
	(1, 'Rojas'),
	(1, 'Roque Pérez'),
	(1, 'Saavedra'),
	(1, 'Saladillo'),
	(1, 'Salliqueló'),
	(1, 'Salto'),
	(1, 'San Andrés de Giles'),
	(1, 'San Antonio de Areco'),
	(1, 'San Antonio de Padua'),
	(1, 'San Bernardo'),
	(1, 'San Cayetano'),
	(1, 'San Clemente del Tuyú'),
	(1, 'San Nicolás'),
	(1, 'San Pedro'),
	(1, 'San Vicente'),
	(1, 'Santa Teresita'),
	(1, 'Suipacha'),
	(1, 'Tandil'),
	(1, 'Tapalqué'),
	(1, 'Tordillo'),
	(1, 'Tornquist'),
	(1, 'Trenque Lauquen'),
	(1, 'Tres Lomas'),
	(1, 'Villa Gesell'),
	(1, 'Villarino'),
	(1, 'Zárate'),
	(2, '11 de Septiembre'),
	(2, '20 de Junio'),
	(2, '25 de Mayo'),
	(2, 'Acassuso'),
	(2, 'Adrogué'),
	(2, 'Aldo Bonzi'),
	(2, 'Área Reserva Cinturón Ecológico'),
	(2, 'Avellaneda'),
	(2, 'Banfield'),
	(2, 'Barrio Parque'),
	(2, 'Barrio Santa Teresita'),
	(2, 'Beccar'),
	(2, 'Bella Vista'),
	(2, 'Berazategui'),
	(2, 'Bernal Este'),
	(2, 'Bernal Oeste'),
	(2, 'Billinghurst'),
	(2, 'Boulogne'),
	(2, 'Burzaco'),
	(2, 'Carapachay'),
	(2, 'Caseros'),
	(2, 'Castelar'),
	(2, 'Churruca'),
	(2, 'Ciudad Evita'),
	(2, 'Ciudad Madero'),
	(2, 'Ciudadela'),
	(2, 'Claypole'),
	(2, 'Crucecita'),
	(2, 'Dock Sud'),
	(2, 'Don Bosco'),
	(2, 'Don Orione'),
	(2, 'El Jagüel'),
	(2, 'El Libertador'),
	(2, 'El Palomar'),
	(2, 'El Tala'),
	(2, 'El Trébol'),
	(2, 'Ezeiza'),
	(2, 'Ezpeleta'),
	(2, 'Florencio Varela'),
	(2, 'Florida'),
	(2, 'Francisco Álvarez'),
	(2, 'Gerli'),
	(2, 'Glew'),
	(2, 'González Catán'),
	(2, 'Gral. Lamadrid'),
	(2, 'Grand Bourg'),
	(2, 'Gregorio de Laferrere'),
	(2, 'Guillermo Enrique Hudson'),
	(2, 'Haedo'),
	(2, 'Hurlingham'),
	(2, 'Ing. Sourdeaux'),
	(2, 'Isidro Casanova'),
	(2, 'Ituzaingó'),
	(2, 'José C. Paz'),
	(2, 'José Ingenieros'),
	(2, 'José Marmol'),
	(2, 'La Lucila'),
	(2, 'La Reja'),
	(2, 'La Tablada'),
	(2, 'Lanús'),
	(2, 'Llavallol'),
	(2, 'Loma Hermosa'),
	(2, 'Lomas de Zamora'),
	(2, 'Lomas del Millón'),
	(2, 'Lomas del Mirador'),
	(2, 'Longchamps'),
	(2, 'Los Polvorines'),
	(2, 'Luis Guillón'),
	(2, 'Malvinas Argentinas'),
	(2, 'Martín Coronado'),
	(2, 'Martínez'),
	(2, 'Merlo'),
	(2, 'Ministro Rivadavia'),
	(2, 'Monte Chingolo'),
	(2, 'Monte Grande'),
	(2, 'Moreno'),
	(2, 'Morón'),
	(2, 'Muñiz'),
	(2, 'Olivos'),
	(2, 'Pablo Nogués'),
	(2, 'Pablo Podestá'),
	(2, 'Paso del Rey'),
	(2, 'Pereyra'),
	(2, 'Piñeiro'),
	(2, 'Plátanos'),
	(2, 'Pontevedra'),
	(2, 'Quilmes'),
	(2, 'Rafael Calzada'),
	(2, 'Rafael Castillo'),
	(2, 'Ramos Mejía'),
	(2, 'Ranelagh'),
	(2, 'Remedios de Escalada'),
	(2, 'Sáenz Peña'),
	(2, 'San Antonio de Padua'),
	(2, 'San Fernando'),
	(2, 'San Francisco Solano'),
	(2, 'San Isidro'),
	(2, 'San José'),
	(2, 'San Justo'),
	(2, 'San Martín'),
	(2, 'San Miguel'),
	(2, 'Santos Lugares'),
	(2, 'Sarandí'),
	(2, 'Sourigues'),
	(2, 'Tapiales'),
	(2, 'Temperley'),
	(2, 'Tigre'),
	(2, 'Tortuguitas'),
	(2, 'Tristán Suárez'),
	(2, 'Trujui'),
	(2, 'Turdera'),
	(2, 'Valentín Alsina'),
	(2, 'Vicente López'),
	(2, 'Villa Adelina'),
	(2, 'Villa Ballester'),
	(2, 'Villa Bosch'),
	(2, 'Villa Caraza'),
	(2, 'Villa Celina'),
	(2, 'Villa Centenario'),
	(2, 'Villa de Mayo'),
	(2, 'Villa Diamante'),
	(2, 'Villa Domínico'),
	(2, 'Villa España'),
	(2, 'Villa Fiorito'),
	(2, 'Villa Guillermina'),
	(2, 'Villa Insuperable'),
	(2, 'Villa José León Suárez'),
	(2, 'Villa La Florida'),
	(2, 'Villa Luzuriaga'),
	(2, 'Villa Martelli'),
	(2, 'Villa Obrera'),
	(2, 'Villa Progreso'),
	(2, 'Villa Raffo'),
	(2, 'Villa Sarmiento'),
	(2, 'Villa Tesei'),
	(2, 'Villa Udaondo'),
	(2, 'Virrey del Pino'),
	(2, 'Wilde'),
	(2, 'William Morris'),
	(3, 'Agronomía'),
	(3, 'Almagro'),
	(3, 'Balvanera'),
	(3, 'Barracas'),
	(3, 'Belgrano'),
	(3, 'Boca'),
	(3, 'Boedo'),
	(3, 'Caballito'),
	(3, 'Chacarita'),
	(3, 'Coghlan'),
	(3, 'Colegiales'),
	(3, 'Constitución'),
	(3, 'Flores'),
	(3, 'Floresta'),
	(3, 'La Paternal'),
	(3, 'Liniers'),
	(3, 'Mataderos'),
	(3, 'Monserrat'),
	(3, 'Monte Castro'),
	(3, 'Nueva Pompeya'),
	(3, 'Núñez'),
	(3, 'Palermo'),
	(3, 'Parque Avellaneda'),
	(3, 'Parque Chacabuco'),
	(3, 'Parque Chas'),
	(3, 'Parque Patricios'),
	(3, 'Puerto Madero'),
	(3, 'Recoleta'),
	(3, 'Retiro'),
	(3, 'Saavedra'),
	(3, 'San Cristóbal'),
	(3, 'San Nicolás'),
	(3, 'San Telmo'),
	(3, 'Vélez Sársfield'),
	(3, 'Versalles'),
	(3, 'Villa Crespo'),
	(3, 'Villa del Parque'),
	(3, 'Villa Devoto'),
	(3, 'Villa Gral. Mitre'),
	(3, 'Villa Lugano'),
	(3, 'Villa Luro'),
	(3, 'Villa Ortúzar'),
	(3, 'Villa Pueyrredón'),
	(3, 'Villa Real'),
	(3, 'Villa Riachuelo'),
	(3, 'Villa Santa Rita'),
	(3, 'Villa Soldati'),
	(3, 'Villa Urquiza'),
	(4, 'Aconquija'),
	(4, 'Ancasti'),
	(4, 'Andalgalá'),
	(4, 'Antofagasta'),
	(4, 'Belén'),
	(4, 'Capayán'),
	(4, 'Capital'),
	(4, '4'),
	(4, 'Corral Quemado'),
	(4, 'El Alto'),
	(4, 'El Rodeo'),
	(4, 'F.Mamerto Esquiú'),
	(4, 'Fiambalá'),
	(4, 'Hualfín'),
	(4, 'Huillapima'),
	(4, 'Icaño'),
	(4, 'La Puerta'),
	(4, 'Las Juntas'),
	(4, 'Londres'),
	(4, 'Los Altos'),
	(4, 'Los Varela'),
	(4, 'Mutquín'),
	(4, 'Paclín'),
	(4, 'Poman'),
	(4, 'Pozo de La Piedra'),
	(4, 'Puerta de Corral'),
	(4, 'Puerta San José'),
	(4, 'Recreo'),
	(4, 'S.F.V de 4'),
	(4, 'San Fernando'),
	(4, 'San Fernando del Valle'),
	(4, 'San José'),
	(4, 'Santa María'),
	(4, 'Santa Rosa'),
	(4, 'Saujil'),
	(4, 'Tapso'),
	(4, 'Tinogasta'),
	(4, 'Valle Viejo'),
	(4, 'Villa Vil'),
	(5, 'Aviá Teraí'),
	(5, 'Barranqueras'),
	(5, 'Basail'),
	(5, 'Campo Largo'),
	(5, 'Capital'),
	(5, 'Capitán Solari'),
	(5, 'Charadai'),
	(5, 'Charata'),
	(5, 'Chorotis'),
	(5, 'Ciervo Petiso'),
	(5, 'Cnel. Du Graty'),
	(5, 'Col. Benítez'),
	(5, 'Col. Elisa'),
	(5, 'Col. Popular'),
	(5, 'Colonias Unidas'),
	(5, 'Concepción'),
	(5, 'Corzuela'),
	(5, 'Cote Lai'),
	(5, 'El Sauzalito'),
	(5, 'Enrique Urien'),
	(5, 'Fontana'),
	(5, 'Fte. Esperanza'),
	(5, 'Gancedo'),
	(5, 'Gral. Capdevila'),
	(5, 'Gral. Pinero'),
	(5, 'Gral. San Martín'),
	(5, 'Gral. Vedia'),
	(5, 'Hermoso Campo'),
	(5, 'I. del Cerrito'),
	(5, 'J.J. Castelli'),
	(5, 'La Clotilde'),
	(5, 'La Eduvigis'),
	(5, 'La Escondida'),
	(5, 'La Leonesa'),
	(5, 'La Tigra'),
	(5, 'La Verde'),
	(5, 'Laguna Blanca'),
	(5, 'Laguna Limpia'),
	(5, 'Lapachito'),
	(5, 'Las Breñas'),
	(5, 'Las Garcitas'),
	(5, 'Las Palmas'),
	(5, 'Los Frentones'),
	(5, 'Machagai'),
	(5, 'Makallé'),
	(5, 'Margarita Belén'),
	(5, 'Miraflores'),
	(5, 'Misión N. Pompeya'),
	(5, 'Napenay'),
	(5, 'Pampa Almirón'),
	(5, 'Pampa del Indio'),
	(5, 'Pampa del Infierno'),
	(5, 'Pdcia. de La Plaza'),
	(5, 'Pdcia. Roca'),
	(5, 'Pdcia. Roque Sáenz Peña'),
	(5, 'Pto. Bermejo'),
	(5, 'Pto. Eva Perón'),
	(5, 'Puero Tirol'),
	(5, 'Puerto Vilelas'),
	(5, 'Quitilipi'),
	(5, 'Resistencia'),
	(5, 'Sáenz Peña'),
	(5, 'Samuhú'),
	(5, 'San Bernardo'),
	(5, 'Santa Sylvina'),
	(5, 'Taco Pozo'),
	(5, 'Tres Isletas'),
	(5, 'Villa Ángela'),
	(5, 'Villa Berthet'),
	(5, 'Villa R. Bermejito'),
	(6, 'Aldea Apeleg'),
	(6, 'Aldea Beleiro'),
	(6, 'Aldea Epulef'),
	(6, 'Alto Río Sengerr'),
	(6, 'Buen Pasto'),
	(6, 'Camarones'),
	(6, 'Carrenleufú'),
	(6, 'Cholila'),
	(6, 'Co. Centinela'),
	(6, 'Colan Conhué'),
	(6, 'Comodoro Rivadavia'),
	(6, 'Corcovado'),
	(6, 'Cushamen'),
	(6, 'Dique F. Ameghino'),
	(6, 'Dolavón'),
	(6, 'Dr. R. Rojas'),
	(6, 'El Hoyo'),
	(6, 'El Maitén'),
	(6, 'Epuyén'),
	(6, 'Esquel'),
	(6, 'Facundo'),
	(6, 'Gaimán'),
	(6, 'Gan Gan'),
	(6, 'Gastre'),
	(6, 'Gdor. Costa'),
	(6, 'Gualjaina'),
	(6, 'J. de San Martín'),
	(6, 'Lago Blanco'),
	(6, 'Lago Puelo'),
	(6, 'Lagunita Salada'),
	(6, 'Las Plumas'),
	(6, 'Los Altares'),
	(6, 'Paso de los Indios'),
	(6, 'Paso del Sapo'),
	(6, 'Pto. Madryn'),
	(6, 'Pto. Pirámides'),
	(6, 'Rada Tilly'),
	(6, 'Rawson'),
	(6, 'Río Mayo'),
	(6, 'Río Pico'),
	(6, 'Sarmiento'),
	(6, 'Tecka'),
	(6, 'Telsen'),
	(6, 'Trelew'),
	(6, 'Trevelin'),
	(6, 'Veintiocho de Julio'),
	(7, 'Achiras'),
	(7, 'Adelia Maria'),
	(7, 'Agua de Oro'),
	(7, 'Alcira Gigena'),
	(7, 'Aldea Santa Maria'),
	(7, 'Alejandro Roca'),
	(7, 'Alejo Ledesma'),
	(7, 'Alicia'),
	(7, 'Almafuerte'),
	(7, 'Alpa Corral'),
	(7, 'Alta Gracia'),
	(7, 'Alto Alegre'),
	(7, 'Alto de Los Quebrachos'),
	(7, 'Altos de Chipion'),
	(7, 'Amboy'),
	(7, 'Ambul'),
	(7, 'Ana Zumaran'),
	(7, 'Anisacate'),
	(7, 'Arguello'),
	(7, 'Arias'),
	(7, 'Arroyito'),
	(7, 'Arroyo Algodon'),
	(7, 'Arroyo Cabral'),
	(7, 'Arroyo Los Patos'),
	(7, 'Assunta'),
	(7, 'Atahona'),
	(7, 'Ausonia'),
	(7, 'Avellaneda'),
	(7, 'Ballesteros'),
	(7, 'Ballesteros Sud'),
	(7, 'Balnearia'),
	(7, 'Bañado de Soto'),
	(7, 'Bell Ville'),
	(7, 'Bengolea'),
	(7, 'Benjamin Gould'),
	(7, 'Berrotaran'),
	(7, 'Bialet Masse'),
	(7, 'Bouwer'),
	(7, 'Brinkmann'),
	(7, 'Buchardo'),
	(7, 'Bulnes'),
	(7, 'Cabalango'),
	(7, 'Calamuchita'),
	(7, 'Calchin'),
	(7, 'Calchin Oeste'),
	(7, 'Calmayo'),
	(7, 'Camilo Aldao'),
	(7, 'Caminiaga'),
	(7, 'Cañada de Luque'),
	(7, 'Cañada de Machado'),
	(7, 'Cañada de Rio Pinto'),
	(7, 'Cañada del Sauce'),
	(7, 'Canals'),
	(7, 'Candelaria Sud'),
	(7, 'Capilla de Remedios'),
	(7, 'Capilla de Siton'),
	(7, 'Capilla del Carmen'),
	(7, 'Capilla del Monte'),
	(7, 'Capital'),
	(7, 'Capitan Gral B. O´Higgins'),
	(7, 'Carnerillo'),
	(7, 'Carrilobo'),
	(7, 'Casa Grande'),
	(7, 'Cavanagh'),
	(7, 'Cerro Colorado'),
	(7, 'Chaján'),
	(7, 'Chalacea'),
	(7, 'Chañar Viejo'),
	(7, 'Chancaní'),
	(7, 'Charbonier'),
	(7, 'Charras'),
	(7, 'Chazón'),
	(7, 'Chilibroste'),
	(7, 'Chucul'),
	(7, 'Chuña'),
	(7, 'Chuña Huasi'),
	(7, 'Churqui Cañada'),
	(7, 'Cienaga Del Coro'),
	(7, 'Cintra'),
	(7, 'Col. Almada'),
	(7, 'Col. Anita'),
	(7, 'Col. Barge'),
	(7, 'Col. Bismark'),
	(7, 'Col. Bremen'),
	(7, 'Col. Caroya'),
	(7, 'Col. Italiana'),
	(7, 'Col. Iturraspe'),
	(7, 'Col. Las Cuatro Esquinas'),
	(7, 'Col. Las Pichanas'),
	(7, 'Col. Marina'),
	(7, 'Col. Prosperidad'),
	(7, 'Col. San Bartolome'),
	(7, 'Col. San Pedro'),
	(7, 'Col. Tirolesa'),
	(7, 'Col. Vicente Aguero'),
	(7, 'Col. Videla'),
	(7, 'Col. Vignaud'),
	(7, 'Col. Waltelina'),
	(7, 'Colazo'),
	(7, 'Comechingones'),
	(7, 'Conlara'),
	(7, 'Copacabana'),
	(7, 'Cordoba Capital'),
	(7, 'Coronel Baigorria'),
	(7, 'Coronel Moldes'),
	(7, 'Corral de Bustos'),
	(7, 'Corralito'),
	(7, 'Cosquín'),
	(7, 'Costa Sacate'),
	(7, 'Cruz Alta'),
	(7, 'Cruz de Caña'),
	(7, 'Cruz del Eje'),
	(7, 'Cuesta Blanca'),
	(7, 'Dean Funes'),
	(7, 'Del Campillo'),
	(7, 'Despeñaderos'),
	(7, 'Devoto'),
	(7, 'Diego de Rojas'),
	(7, 'Dique Chico'),
	(7, 'El Arañado'),
	(7, 'El Brete'),
	(7, 'El Chacho'),
	(7, 'El Crispín'),
	(7, 'El Fortín'),
	(7, 'El Manzano'),
	(7, 'El Rastreador'),
	(7, 'El Rodeo'),
	(7, 'El Tío'),
	(7, 'Elena'),
	(7, 'Embalse'),
	(7, 'Esquina'),
	(7, 'Estación Gral. Paz'),
	(7, 'Estación Juárez Celman'),
	(7, 'Estancia de Guadalupe'),
	(7, 'Estancia Vieja'),
	(7, 'Etruria'),
	(7, 'Eufrasio Loza'),
	(7, 'Falda del Carmen'),
	(7, 'Freyre'),
	(7, 'Gral. Baldissera'),
	(7, 'Gral. Cabrera'),
	(7, 'Gral. Deheza'),
	(7, 'Gral. Fotheringham'),
	(7, 'Gral. Levalle'),
	(7, 'Gral. Roca'),
	(7, 'Guanaco Muerto'),
	(7, 'Guasapampa'),
	(7, 'Guatimozin'),
	(7, 'Gutenberg'),
	(7, 'Hernando'),
	(7, 'Huanchillas'),
	(7, 'Huerta Grande'),
	(7, 'Huinca Renanco'),
	(7, 'Idiazabal'),
	(7, 'Impira'),
	(7, 'Inriville'),
	(7, 'Isla Verde'),
	(7, 'Italó'),
	(7, 'James Craik'),
	(7, 'Jesús María'),
	(7, 'Jovita'),
	(7, 'Justiniano Posse'),
	(7, 'Km 658'),
	(7, 'L. V. Mansilla'),
	(7, 'La Batea'),
	(7, 'La Calera'),
	(7, 'La Carlota'),
	(7, 'La Carolina'),
	(7, 'La Cautiva'),
	(7, 'La Cesira'),
	(7, 'La Cruz'),
	(7, 'La Cumbre'),
	(7, 'La Cumbrecita'),
	(7, 'La Falda'),
	(7, 'La Francia'),
	(7, 'La Granja'),
	(7, 'La Higuera'),
	(7, 'La Laguna'),
	(7, 'La Paisanita'),
	(7, 'La Palestina'),
	(7, '12'),
	(7, 'La Paquita'),
	(7, 'La Para'),
	(7, 'La Paz'),
	(7, 'La Playa'),
	(7, 'La Playosa'),
	(7, 'La Población'),
	(7, 'La Posta'),
	(7, 'La Puerta'),
	(7, 'La Quinta'),
	(7, 'La Rancherita'),
	(7, 'La Rinconada'),
	(7, 'La Serranita'),
	(7, 'La Tordilla'),
	(7, 'Laborde'),
	(7, 'Laboulaye'),
	(7, 'Laguna Larga'),
	(7, 'Las Acequias'),
	(7, 'Las Albahacas'),
	(7, 'Las Arrias'),
	(7, 'Las Bajadas'),
	(7, 'Las Caleras'),
	(7, 'Las Calles'),
	(7, 'Las Cañadas'),
	(7, 'Las Gramillas'),
	(7, 'Las Higueras'),
	(7, 'Las Isletillas'),
	(7, 'Las Junturas'),
	(7, 'Las Palmas'),
	(7, 'Las Peñas'),
	(7, 'Las Peñas Sud'),
	(7, 'Las Perdices'),
	(7, 'Las Playas'),
	(7, 'Las Rabonas'),
	(7, 'Las Saladas'),
	(7, 'Las Tapias'),
	(7, 'Las Varas'),
	(7, 'Las Varillas'),
	(7, 'Las Vertientes'),
	(7, 'Leguizamón'),
	(7, 'Leones'),
	(7, 'Los Cedros'),
	(7, 'Los Cerrillos'),
	(7, 'Los Chañaritos (C.E)'),
	(7, 'Los Chanaritos (R.S)'),
	(7, 'Los Cisnes'),
	(7, 'Los Cocos'),
	(7, 'Los Cóndores'),
	(7, 'Los Hornillos'),
	(7, 'Los Hoyos'),
	(7, 'Los Mistoles'),
	(7, 'Los Molinos'),
	(7, 'Los Pozos'),
	(7, 'Los Reartes'),
	(7, 'Los Surgentes'),
	(7, 'Los Talares'),
	(7, 'Los Zorros'),
	(7, 'Lozada'),
	(7, 'Luca'),
	(7, 'Luque'),
	(7, 'Luyaba'),
	(7, 'Malagueño'),
	(7, 'Malena'),
	(7, 'Malvinas Argentinas'),
	(7, 'Manfredi'),
	(7, 'Maquinista Gallini'),
	(7, 'Marcos Juárez'),
	(7, 'Marull'),
	(7, 'Matorrales'),
	(7, 'Mattaldi'),
	(7, 'Mayu Sumaj'),
	(7, 'Media Naranja'),
	(7, 'Melo'),
	(7, 'Mendiolaza'),
	(7, 'Mi Granja'),
	(7, 'Mina Clavero'),
	(7, 'Miramar'),
	(7, 'Morrison'),
	(7, 'Morteros'),
	(7, 'Mte. Buey'),
	(7, 'Mte. Cristo'),
	(7, 'Mte. De Los Gauchos'),
	(7, 'Mte. Leña'),
	(7, 'Mte. Maíz'),
	(7, 'Mte. Ralo'),
	(7, 'Nicolás Bruzone'),
	(7, 'Noetinger'),
	(7, 'Nono'),
	(7, 'Nueva 7'),
	(7, 'Obispo Trejo'),
	(7, 'Olaeta'),
	(7, 'Oliva'),
	(7, 'Olivares San Nicolás'),
	(7, 'Onagolty'),
	(7, 'Oncativo'),
	(7, 'Ordoñez'),
	(7, 'Pacheco De Melo'),
	(7, 'Pampayasta N.'),
	(7, 'Pampayasta S.'),
	(7, 'Panaholma'),
	(7, 'Pascanas'),
	(7, 'Pasco'),
	(7, 'Paso del Durazno'),
	(7, 'Paso Viejo'),
	(7, 'Pilar'),
	(7, 'Pincén'),
	(7, 'Piquillín'),
	(7, 'Plaza de Mercedes'),
	(7, 'Plaza Luxardo'),
	(7, 'Porteña'),
	(7, 'Potrero de Garay'),
	(7, 'Pozo del Molle'),
	(7, 'Pozo Nuevo'),
	(7, 'Pueblo Italiano'),
	(7, 'Puesto de Castro'),
	(7, 'Punta del Agua'),
	(7, 'Quebracho Herrado'),
	(7, 'Quilino'),
	(7, 'Rafael García'),
	(7, 'Ranqueles'),
	(7, 'Rayo Cortado'),
	(7, 'Reducción'),
	(7, 'Rincón'),
	(7, 'Río Bamba'),
	(7, 'Río Ceballos'),
	(7, 'Río Cuarto'),
	(7, 'Río de Los Sauces'),
	(7, 'Río Primero'),
	(7, 'Río Segundo'),
	(7, 'Río Tercero'),
	(7, 'Rosales'),
	(7, 'Rosario del Saladillo'),
	(7, 'Sacanta'),
	(7, 'Sagrada Familia'),
	(7, 'Saira'),
	(7, 'Saladillo'),
	(7, 'Saldán'),
	(7, 'Salsacate'),
	(7, 'Salsipuedes'),
	(7, 'Sampacho'),
	(7, 'San Agustín'),
	(7, 'San Antonio de Arredondo'),
	(7, 'San Antonio de Litín'),
	(7, 'San Basilio'),
	(7, 'San Carlos Minas'),
	(7, 'San Clemente'),
	(7, 'San Esteban'),
	(7, 'San Francisco'),
	(7, 'San Ignacio'),
	(7, 'San Javier'),
	(7, 'San Jerónimo'),
	(7, 'San Joaquín'),
	(7, 'San José de La Dormida'),
	(7, 'San José de Las Salinas'),
	(7, 'San Lorenzo'),
	(7, 'San Marcos Sierras'),
	(7, 'San Marcos Sud'),
	(7, 'San Pedro'),
	(7, 'San Pedro N.'),
	(7, 'San Roque'),
	(7, 'San Vicente'),
	(7, 'Santa Catalina'),
	(7, 'Santa Elena'),
	(7, 'Santa Eufemia'),
	(7, 'Santa Maria'),
	(7, 'Sarmiento'),
	(7, 'Saturnino M.Laspiur'),
	(7, 'Sauce Arriba'),
	(7, 'Sebastián Elcano'),
	(7, 'Seeber'),
	(7, 'Segunda Usina'),
	(7, 'Serrano'),
	(7, 'Serrezuela'),
	(7, 'Sgo. Temple'),
	(7, 'Silvio Pellico'),
	(7, 'Simbolar'),
	(7, 'Sinsacate'),
	(7, 'Sta. Rosa de Calamuchita'),
	(7, 'Sta. Rosa de Río Primero'),
	(7, 'Suco'),
	(7, 'Tala Cañada'),
	(7, 'Tala Huasi'),
	(7, 'Talaini'),
	(7, 'Tancacha'),
	(7, 'Tanti'),
	(7, 'Ticino'),
	(7, 'Tinoco'),
	(7, 'Tío Pujio'),
	(7, 'Toledo'),
	(7, 'Toro Pujio'),
	(7, 'Tosno'),
	(7, 'Tosquita'),
	(7, 'Tránsito'),
	(7, 'Tuclame'),
	(7, 'Tutti'),
	(7, 'Ucacha'),
	(7, 'Unquillo'),
	(7, 'Valle de Anisacate'),
	(7, 'Valle Hermoso'),
	(7, 'Vélez Sarfield'),
	(7, 'Viamonte'),
	(7, 'Vicuña Mackenna'),
	(7, 'Villa Allende'),
	(7, 'Villa Amancay'),
	(7, 'Villa Ascasubi'),
	(7, 'Villa Candelaria N.'),
	(7, 'Villa Carlos Paz'),
	(7, 'Villa Cerro Azul'),
	(7, 'Villa Ciudad de América'),
	(7, 'Villa Ciudad Pque Los Reartes'),
	(7, 'Villa Concepción del Tío'),
	(7, 'Villa Cura Brochero'),
	(7, 'Villa de Las Rosas'),
	(7, 'Villa de María'),
	(7, 'Villa de Pocho'),
	(7, 'Villa de Soto'),
	(7, 'Villa del Dique'),
	(7, 'Villa del Prado'),
	(7, 'Villa del Rosario'),
	(7, 'Villa del Totoral'),
	(7, 'Villa Dolores'),
	(7, 'Villa El Chancay'),
	(7, 'Villa Elisa'),
	(7, 'Villa Flor Serrana'),
	(7, 'Villa Fontana'),
	(7, 'Villa Giardino'),
	(7, 'Villa Gral. Belgrano'),
	(7, 'Villa Gutierrez'),
	(7, 'Villa Huidobro'),
	(7, 'Villa La Bolsa'),
	(7, 'Villa Los Aromos'),
	(7, 'Villa Los Patos'),
	(7, 'Villa María'),
	(7, 'Villa Nueva'),
	(7, 'Villa Pque. Santa Ana'),
	(7, 'Villa Pque. Siquiman'),
	(7, 'Villa Quillinzo'),
	(7, 'Villa Rossi'),
	(7, 'Villa Rumipal'),
	(7, 'Villa San Esteban'),
	(7, 'Villa San Isidro'),
	(7, 'Villa 21'),
	(7, 'Villa Sarmiento (G.R)'),
	(7, 'Villa Sarmiento (S.A)'),
	(7, 'Villa Tulumba'),
	(7, 'Villa Valeria'),
	(7, 'Villa Yacanto'),
	(7, 'Washington'),
	(7, 'Wenceslao Escalante'),
	(7, 'Ycho Cruz Sierras'),
	(8, 'Alvear'),
	(8, 'Bella Vista'),
	(8, 'Berón de Astrada'),
	(8, 'Bonpland'),
	(8, 'Caá Cati'),
	(8, 'Capital'),
	(8, 'Chavarría'),
	(8, 'Col. C. Pellegrini'),
	(8, 'Col. Libertad'),
	(8, 'Col. Liebig'),
	(8, 'Col. Sta Rosa'),
	(8, 'Concepción'),
	(8, 'Cruz de Los Milagros'),
	(8, 'Curuzú-Cuatiá'),
	(8, 'Empedrado'),
	(8, 'Esquina'),
	(8, 'Estación Torrent'),
	(8, 'Felipe Yofré'),
	(8, 'Garruchos'),
	(8, 'Gdor. Agrónomo'),
	(8, 'Gdor. Martínez'),
	(8, 'Goya'),
	(8, 'Guaviravi'),
	(8, 'Herlitzka'),
	(8, 'Ita-Ibate'),
	(8, 'Itatí'),
	(8, 'Ituzaingó'),
	(8, 'José Rafael Gómez'),
	(8, 'Juan Pujol'),
	(8, 'La Cruz'),
	(8, 'Lavalle'),
	(8, 'Lomas de Vallejos'),
	(8, 'Loreto'),
	(8, 'Mariano I. Loza'),
	(8, 'Mburucuyá'),
	(8, 'Mercedes'),
	(8, 'Mocoretá'),
	(8, 'Mte. Caseros'),
	(8, 'Nueve de Julio'),
	(8, 'Palmar Grande'),
	(8, 'Parada Pucheta'),
	(8, 'Paso de La Patria'),
	(8, 'Paso de Los Libres'),
	(8, 'Pedro R. Fernandez'),
	(8, 'Perugorría'),
	(8, 'Pueblo Libertador'),
	(8, 'Ramada Paso'),
	(8, 'Riachuelo'),
	(8, 'Saladas'),
	(8, 'San Antonio'),
	(8, 'San Carlos'),
	(8, 'San Cosme'),
	(8, 'San Lorenzo'),
	(8, '20 del Palmar'),
	(8, 'San Miguel'),
	(8, 'San Roque'),
	(8, 'Santa Ana'),
	(8, 'Santa Lucía'),
	(8, 'Santo Tomé'),
	(8, 'Sauce'),
	(8, 'Tabay'),
	(8, 'Tapebicuá'),
	(8, 'Tatacua'),
	(8, 'Virasoro'),
	(8, 'Yapeyú'),
	(8, 'Yataití Calle'),
	(9, 'Alarcón'),
	(9, 'Alcaraz'),
	(9, 'Alcaraz N.'),
	(9, 'Alcaraz S.'),
	(9, 'Aldea Asunción'),
	(9, 'Aldea Brasilera'),
	(9, 'Aldea Elgenfeld'),
	(9, 'Aldea Grapschental'),
	(9, 'Aldea Ma. Luisa'),
	(9, 'Aldea Protestante'),
	(9, 'Aldea Salto'),
	(9, 'Aldea San Antonio (G)'),
	(9, 'Aldea San Antonio (P)'),
	(9, 'Aldea 19'),
	(9, 'Aldea San Miguel'),
	(9, 'Aldea San Rafael'),
	(9, 'Aldea Spatzenkutter'),
	(9, 'Aldea Sta. María'),
	(9, 'Aldea Sta. Rosa'),
	(9, 'Aldea Valle María')
INSERT INTO Localidades (IDProvincia, Descripcion) VALUES	
	(9, 'Altamirano Sur'),
	(9, 'Antelo'),
	(9, 'Antonio Tomás'),
	(9, 'Aranguren'),
	(9, 'Arroyo Barú'),
	(9, 'Arroyo Burgos'),
	(9, 'Arroyo Clé'),
	(9, 'Arroyo Corralito'),
	(9, 'Arroyo del Medio'),
	(9, 'Arroyo Maturrango'),
	(9, 'Arroyo Palo Seco'),
	(9, 'Banderas'),
	(9, 'Basavilbaso'),
	(9, 'Betbeder'),
	(9, 'Bovril'),
	(9, 'Caseros'),
	(9, 'Ceibas'),
	(9, 'Cerrito'),
	(9, 'Chajarí'),
	(9, 'Chilcas'),
	(9, 'Clodomiro Ledesma'),
	(9, 'Col. Alemana'),
	(9, 'Col. Avellaneda'),
	(9, 'Col. Avigdor'),
	(9, 'Col. Ayuí'),
	(9, 'Col. Baylina'),
	(9, 'Col. Carrasco'),
	(9, 'Col. Celina'),
	(9, 'Col. Cerrito'),
	(9, 'Col. Crespo'),
	(9, 'Col. Elia'),
	(9, 'Col. Ensayo'),
	(9, 'Col. Gral. Roca'),
	(9, 'Col. La Argentina'),
	(9, 'Col. Merou'),
	(9, 'Col. Oficial Nª3'),
	(9, 'Col. Oficial Nº13'),
	(9, 'Col. Oficial Nº14'),
	(9, 'Col. Oficial Nº5'),
	(9, 'Col. Reffino'),
	(9, 'Col. Tunas'),
	(9, 'Col. Viraró'),
	(9, 'Colón'),
	(9, 'Concepción del Uruguay'),
	(9, 'Concordia'),
	(9, 'Conscripto Bernardi'),
	(9, 'Costa Grande'),
	(9, 'Costa San Antonio'),
	(9, 'Costa Uruguay N.'),
	(9, 'Costa Uruguay S.'),
	(9, 'Crespo'),
	(9, 'Crucecitas 3ª'),
	(9, 'Crucecitas 7ª'),
	(9, 'Crucecitas 8ª'),
	(9, 'Cuchilla Redonda'),
	(9, 'Curtiembre'),
	(9, 'Diamante'),
	(9, 'Distrito 6º'),
	(9, 'Distrito Chañar'),
	(9, 'Distrito Chiqueros'),
	(9, 'Distrito Cuarto'),
	(9, 'Distrito Diego López'),
	(9, 'Distrito Pajonal'),
	(9, 'Distrito Sauce'),
	(9, 'Distrito Tala'),
	(9, 'Distrito Talitas'),
	(9, 'Don Cristóbal 1ª Sección'),
	(9, 'Don Cristóbal 2ª Sección'),
	(9, 'Durazno'),
	(9, 'El Cimarrón'),
	(9, 'El Gramillal'),
	(9, 'El Palenque'),
	(9, 'El Pingo'),
	(9, 'El Quebracho'),
	(9, 'El Redomón'),
	(9, 'El Solar'),
	(9, 'Enrique Carbo'),
	(9, '9'),
	(9, 'Espinillo N.'),
	(9, 'Estación Campos'),
	(9, 'Estación Escriña'),
	(9, 'Estación Lazo'),
	(9, 'Estación Raíces'),
	(9, 'Estación Yerúa'),
	(9, 'Estancia Grande'),
	(9, 'Estancia Líbaros'),
	(9, 'Estancia Racedo'),
	(9, 'Estancia Solá'),
	(9, 'Estancia Yuquerí'),
	(9, 'Estaquitas'),
	(9, 'Faustino M. Parera'),
	(9, 'Febre'),
	(9, 'Federación'),
	(9, 'Federal'),
	(9, 'Gdor. Echagüe'),
	(9, 'Gdor. Mansilla'),
	(9, 'Gilbert'),
	(9, 'González Calderón'),
	(9, 'Gral. Almada'),
	(9, 'Gral. Alvear'),
	(9, 'Gral. Campos'),
	(9, 'Gral. Galarza'),
	(9, 'Gral. Ramírez'),
	(9, 'Gualeguay'),
	(9, 'Gualeguaychú'),
	(9, 'Gualeguaycito'),
	(9, 'Guardamonte'),
	(9, 'Hambis'),
	(9, 'Hasenkamp'),
	(9, 'Hernandarias'),
	(9, 'Hernández'),
	(9, 'Herrera'),
	(9, 'Hinojal'),
	(9, 'Hocker'),
	(9, 'Ing. Sajaroff'),
	(9, 'Irazusta'),
	(9, 'Isletas'),
	(9, 'J.J De Urquiza'),
	(9, 'Jubileo'),
	(9, 'La Clarita'),
	(9, 'La Criolla'),
	(9, 'La Esmeralda'),
	(9, 'La Florida'),
	(9, 'La Fraternidad'),
	(9, 'La Hierra'),
	(9, 'La Ollita'),
	(9, 'La Paz'),
	(9, 'La Picada'),
	(9, 'La Providencia'),
	(9, 'La Verbena'),
	(9, 'Laguna Benítez'),
	(9, 'Larroque'),
	(9, 'Las Cuevas'),
	(9, 'Las Garzas'),
	(9, 'Las Guachas'),
	(9, 'Las Mercedes'),
	(9, 'Las Moscas'),
	(9, 'Las Mulitas'),
	(9, 'Las Toscas'),
	(9, 'Laurencena'),
	(9, 'Libertador San Martín'),
	(9, 'Loma Limpia'),
	(9, 'Los Ceibos'),
	(9, 'Los Charruas'),
	(9, 'Los Conquistadores'),
	(9, 'Lucas González'),
	(9, 'Lucas N.'),
	(9, 'Lucas S. 1ª'),
	(9, 'Lucas S. 2ª'),
	(9, 'Maciá'),
	(9, 'María Grande'),
	(9, 'María Grande 2ª'),
	(9, 'Médanos'),
	(9, 'Mojones N.'),
	(9, 'Mojones S.'),
	(9, 'Molino Doll'),
	(9, 'Monte Redondo'),
	(9, 'Montoya'),
	(9, 'Mulas Grandes'),
	(9, 'Ñancay'),
	(9, 'Nogoyá'),
	(9, 'Nueva Escocia'),
	(9, 'Nueva Vizcaya'),
	(9, 'Ombú'),
	(9, 'Oro Verde'),
	(9, 'Paraná'),
	(9, 'Pasaje Guayaquil'),
	(9, 'Pasaje Las Tunas'),
	(9, 'Paso de La Arena'),
	(9, 'Paso de La Laguna'),
	(9, 'Paso de Las Piedras'),
	(9, 'Paso Duarte'),
	(9, 'Pastor Britos'),
	(9, 'Pedernal'),
	(9, 'Perdices'),
	(9, 'Picada Berón'),
	(9, 'Piedras Blancas'),
	(9, 'Primer Distrito Cuchilla'),
	(9, 'Primero de Mayo'),
	(9, 'Pronunciamiento'),
	(9, 'Pto. Algarrobo'),
	(9, 'Pto. Ibicuy'),
	(9, 'Pueblo Brugo'),
	(9, 'Pueblo Cazes'),
	(9, 'Pueblo Gral. Belgrano'),
	(9, 'Pueblo Liebig'),
	(9, 'Puerto Yeruá'),
	(9, 'Punta del Monte'),
	(9, 'Quebracho'),
	(9, 'Quinto Distrito'),
	(9, 'Raices Oeste'),
	(9, 'Rincón de Nogoyá'),
	(9, 'Rincón del Cinto'),
	(9, 'Rincón del Doll'),
	(9, 'Rincón del Gato'),
	(9, 'Rocamora'),
	(9, 'Rosario del Tala'),
	(9, 'San Benito'),
	(9, 'San Cipriano'),
	(9, 'San Ernesto'),
	(9, 'San Gustavo'),
	(9, 'San Jaime'),
	(9, 'San José'),
	(9, 'San José de Feliciano'),
	(9, 'San Justo'),
	(9, 'San Marcial'),
	(9, 'San Pedro'),
	(9, 'San Ramírez'),
	(9, 'San Ramón'),
	(9, 'San Roque'),
	(9, 'San Salvador'),
	(9, 'San Víctor'),
	(9, 'Santa Ana'),
	(9, 'Santa Anita'),
	(9, 'Santa Elena'),
	(9, 'Santa Lucía'),
	(9, 'Santa Luisa'),
	(9, 'Sauce de Luna'),
	(9, 'Sauce Montrull'),
	(9, 'Sauce Pinto'),
	(9, 'Sauce Sur'),
	(9, 'Seguí'),
	(9, 'Sir Leonard'),
	(9, 'Sosa'),
	(9, 'Tabossi'),
	(9, 'Tezanos Pinto'),
	(9, 'Ubajay'),
	(9, 'Urdinarrain'),
	(9, 'Veinte de Septiembre'),
	(9, 'Viale'),
	(9, 'Victoria'),
	(9, 'Villa Clara'),
	(9, 'Villa del Rosario'),
	(9, 'Villa Domínguez'),
	(9, 'Villa Elisa'),
	(9, 'Villa Fontana'),
	(9, 'Villa Gdor. Etchevehere'),
	(9, 'Villa Mantero'),
	(9, 'Villa Paranacito'),
	(9, 'Villa Urquiza'),
	(9, 'Villaguay'),
	(9, 'Walter Moss'),
	(9, 'Yacaré'),
	(9, 'Yeso Oeste'),
	(10, 'Buena Vista'),
	(10, 'Clorinda'),
	(10, 'Col. Pastoril'),
	(10, 'Cte. Fontana'),
	(10, 'El Colorado'),
	(10, 'El Espinillo'),
	(10, 'Estanislao Del Campo'),
	(10, '10'),
	(10, 'Fortín Lugones'),
	(10, 'Gral. Lucio V. Mansilla'),
	(10, 'Gral. Manuel Belgrano'),
	(10, 'Gral. Mosconi'),
	(10, 'Gran Guardia'),
	(10, 'Herradura'),
	(10, 'Ibarreta'),
	(10, 'Ing. Juárez'),
	(10, 'Laguna Blanca'),
	(10, 'Laguna Naick Neck'),
	(10, 'Laguna Yema'),
	(10, 'Las Lomitas'),
	(10, 'Los Chiriguanos'),
	(10, 'Mayor V. Villafañe'),
	(10, 'Misión San Fco.'),
	(10, 'Palo Santo'),
	(10, 'Pirané'),
	(10, 'Pozo del Maza'),
	(10, 'Riacho He-He'),
	(10, 'San Hilario'),
	(10, 'San Martín II'),
	(10, 'Siete Palmas'),
	(10, 'Subteniente Perín'),
	(10, 'Tres Lagunas'),
	(10, 'Villa Dos Trece'),
	(10, 'Villa Escolar'),
	(10, 'Villa Gral. Güemes'),
	(11, 'Abdon Castro Tolay'),
	(11, 'Abra Pampa'),
	(11, 'Abralaite'),
	(11, 'Aguas Calientes'),
	(11, 'Arrayanal'),
	(11, 'Barrios'),
	(11, 'Caimancito'),
	(11, 'Calilegua'),
	(11, 'Cangrejillos'),
	(11, 'Caspala'),
	(11, 'Catuá'),
	(11, 'Cieneguillas'),
	(11, 'Coranzulli'),
	(11, 'Cusi-Cusi'),
	(11, 'El Aguilar'),
	(11, 'El Carmen'),
	(11, 'El Cóndor'),
	(11, 'El Fuerte'),
	(11, 'El Piquete'),
	(11, 'El Talar'),
	(11, 'Fraile Pintado'),
	(11, 'Hipólito Yrigoyen'),
	(11, 'Huacalera'),
	(11, 'Humahuaca'),
	(11, 'La Esperanza'),
	(11, 'La Mendieta'),
	(11, 'La Quiaca'),
	(11, 'Ledesma'),
	(11, 'Libertador Gral. San Martin'),
	(11, 'Maimara'),
	(11, 'Mina Pirquitas'),
	(11, 'Monterrico'),
	(11, 'Palma Sola'),
	(11, 'Palpalá'),
	(11, 'Pampa Blanca'),
	(11, 'Pampichuela'),
	(11, 'Perico'),
	(11, 'Puesto del Marqués'),
	(11, 'Puesto Viejo'),
	(11, 'Pumahuasi'),
	(11, 'Purmamarca'),
	(11, 'Rinconada'),
	(11, 'Rodeitos'),
	(11, 'Rosario de Río Grande'),
	(11, 'San Antonio'),
	(11, 'San Francisco'),
	(11, 'San Pedro'),
	(11, 'San Rafael'),
	(11, 'San Salvador'),
	(11, 'Santa Ana'),
	(11, 'Santa Catalina'),
	(11, 'Santa Clara'),
	(11, 'Susques'),
	(11, 'Tilcara'),
	(11, 'Tres Cruces'),
	(11, 'Tumbaya'),
	(11, 'Valle Grande'),
	(11, 'Vinalito'),
	(11, 'Volcán'),
	(11, 'Yala'),
	(11, 'Yaví'),
	(11, 'Yuto'),
	(12, 'Abramo'),
	(12, 'Adolfo Van Praet'),
	(12, 'Agustoni'),
	(12, 'Algarrobo del Aguila'),
	(12, 'Alpachiri'),
	(12, 'Alta Italia'),
	(12, 'Anguil'),
	(12, 'Arata'),
	(12, 'Ataliva Roca'),
	(12, 'Bernardo Larroude'),
	(12, 'Bernasconi'),
	(12, 'Caleufú'),
	(12, 'Carro Quemado'),
	(12, 'Catriló'),
	(12, 'Ceballos'),
	(12, 'Chacharramendi'),
	(12, 'Col. Barón'),
	(12, 'Col. Santa María'),
	(12, 'Conhelo'),
	(12, 'Coronel Hilario Lagos'),
	(12, 'Cuchillo-Có'),
	(12, 'Doblas'),
	(12, 'Dorila'),
	(12, 'Eduardo Castex'),
	(12, 'Embajador Martini'),
	(12, 'Falucho'),
	(12, 'Gral. Acha'),
	(12, 'Gral. Manuel Campos'),
	(12, 'Gral. Pico'),
	(12, 'Guatraché'),
	(12, 'Ing. Luiggi'),
	(12, 'Intendente Alvear'),
	(12, 'Jacinto Arauz'),
	(12, 'La Adela'),
	(12, 'La Humada'),
	(12, 'La Maruja'),
	(12, '12'),
	(12, 'La Reforma'),
	(12, 'Limay Mahuida'),
	(12, 'Lonquimay'),
	(12, 'Loventuel'),
	(12, 'Luan Toro'),
	(12, 'Macachín'),
	(12, 'Maisonnave'),
	(12, 'Mauricio Mayer'),
	(12, 'Metileo'),
	(12, 'Miguel Cané'),
	(12, 'Miguel Riglos'),
	(12, 'Monte Nievas'),
	(12, 'Parera'),
	(12, 'Perú'),
	(12, 'Pichi-Huinca'),
	(12, 'Puelches'),
	(12, 'Puelén'),
	(12, 'Quehue'),
	(12, 'Quemú Quemú'),
	(12, 'Quetrequén'),
	(12, 'Rancul'),
	(12, 'Realicó'),
	(12, 'Relmo'),
	(12, 'Rolón'),
	(12, 'Rucanelo'),
	(12, 'Sarah'),
	(12, 'Speluzzi'),
	(12, 'Sta. Isabel'),
	(12, 'Sta. Rosa'),
	(12, 'Sta. Teresa'),
	(12, 'Telén'),
	(12, 'Toay'),
	(12, 'Tomas M. de Anchorena'),
	(12, 'Trenel'),
	(12, 'Unanue'),
	(12, 'Uriburu'),
	(12, 'Veinticinco de Mayo'),
	(12, 'Vertiz'),
	(12, 'Victorica'),
	(12, 'Villa Mirasol'),
	(12, 'Winifreda'),
	(13, 'Arauco'),
	(13, 'Capital'),
	(13, 'Castro Barros'),
	(13, 'Chamical'),
	(13, 'Chilecito'),
	(13, 'Coronel F. Varela'),
	(13, 'Famatina'),
	(13, 'Gral. A.V.Peñaloza'),
	(13, 'Gral. Belgrano'),
	(13, 'Gral. J.F. Quiroga'),
	(13, 'Gral. Lamadrid'),
	(13, 'Gral. Ocampo'),
	(13, 'Gral. San Martín'),
	(13, 'Independencia'),
	(13, 'Rosario Penaloza'),
	(13, 'San Blas de Los Sauces'),
	(13, 'Sanagasta'),
	(13, 'Vinchina'),
	(14, 'Capital'),
	(14, 'Chacras de Coria'),
	(14, 'Dorrego'),
	(14, 'Gllen'),
	(14, 'Godoy Cruz'),
	(14, 'Gral. Alvear'),
	(14, 'Guaymallén'),
	(14, 'Junín'),
	(14, 'La Paz'),
	(14, 'Las Heras'),
	(14, 'Lavalle'),
	(14, 'Luján'),
	(14, 'Luján De Cuyo'),
	(14, 'Maipú'),
	(14, 'Malargüe'),
	(14, 'Rivadavia'),
	(14, 'San Carlos'),
	(14, 'San Martín'),
	(14, 'San Rafael'),
	(14, 'Sta. Rosa'),
	(14, 'Tunuyán'),
	(14, 'Tupungato'),
	(14, 'Villa Nueva'),
	(15, 'Alba Posse'),
	(15, 'Almafuerte'),
	(15, 'Apóstoles'),
	(15, 'Aristóbulo Del Valle'),
	(15, 'Arroyo Del Medio'),
	(15, 'Azara'),
	(15, 'Bdo. De Irigoyen'),
	(15, 'Bonpland'),
	(15, 'Caá Yari'),
	(15, 'Campo Grande'),
	(15, 'Campo Ramón'),
	(15, 'Campo Viera'),
	(15, 'Candelaria'),
	(15, 'Capioví'),
	(15, 'Caraguatay'),
	(15, 'Cdte. Guacurarí'),
	(15, 'Cerro Azul'),
	(15, 'Cerro Corá'),
	(15, 'Col. Alberdi'),
	(15, 'Col. Aurora'),
	(15, 'Col. Delicia'),
	(15, 'Col. Polana'),
	(15, 'Col. Victoria'),
	(15, 'Col. Wanda'),
	(15, 'Concepción De La Sierra'),
	(15, 'Corpus'),
	(15, 'Dos Arroyos'),
	(15, 'Dos de Mayo'),
	(15, 'El Alcázar'),
	(15, 'El Dorado'),
	(15, 'El Soberbio'),
	(15, 'Esperanza'),
	(15, 'F. Ameghino'),
	(15, 'Fachinal'),
	(15, 'Garuhapé'),
	(15, 'Garupá'),
	(15, 'Gdor. López'),
	(15, 'Gdor. Roca'),
	(15, 'Gral. Alvear'),
	(15, 'Gral. Urquiza'),
	(15, 'Guaraní'),
	(15, 'H. Yrigoyen'),
	(15, 'Iguazú'),
	(15, 'Itacaruaré'),
	(15, 'Jardín América'),
	(15, 'Leandro N. Alem'),
	(15, 'Libertad'),
	(15, 'Loreto'),
	(15, 'Los Helechos'),
	(15, 'Mártires'),
	(15, '15'),
	(15, 'Mojón Grande'),
	(15, 'Montecarlo'),
	(15, 'Nueve de Julio'),
	(15, 'Oberá'),
	(15, 'Olegario V. Andrade'),
	(15, 'Panambí'),
	(15, 'Posadas'),
	(15, 'Profundidad'),
	(15, 'Pto. Iguazú'),
	(15, 'Pto. Leoni'),
	(15, 'Pto. Piray'),
	(15, 'Pto. Rico'),
	(15, 'Ruiz de Montoya'),
	(15, 'San Antonio'),
	(15, 'San Ignacio'),
	(15, 'San Javier'),
	(15, 'San José'),
	(15, 'San Martín'),
	(15, 'San Pedro'),
	(15, 'San Vicente'),
	(15, 'Santiago De Liniers'),
	(15, 'Santo Pipo'),
	(15, 'Sta. Ana'),
	(15, 'Sta. María'),
	(15, 'Tres Capones'),
	(15, 'Veinticinco de Mayo'),
	(15, 'Wanda'),
	(16, 'Aguada San Roque'),
	(16, 'Aluminé'),
	(16, 'Andacollo'),
	(16, 'Añelo'),
	(16, 'Bajada del Agrio'),
	(16, 'Barrancas'),
	(16, 'Buta Ranquil'),
	(16, 'Capital'),
	(16, 'Caviahué'),
	(16, 'Centenario'),
	(16, 'Chorriaca'),
	(16, 'Chos Malal'),
	(16, 'Cipolletti'),
	(16, 'Covunco Abajo'),
	(16, 'Coyuco Cochico'),
	(16, 'Cutral Có'),
	(16, 'El Cholar'),
	(16, 'El Huecú'),
	(16, 'El Sauce'),
	(16, 'Guañacos'),
	(16, 'Huinganco'),
	(16, 'Las Coloradas'),
	(16, 'Las Lajas'),
	(16, 'Las Ovejas'),
	(16, 'Loncopué'),
	(16, 'Los Catutos'),
	(16, 'Los Chihuidos'),
	(16, 'Los Miches'),
	(16, 'Manzano Amargo'),
	(16, '16'),
	(16, 'Octavio Pico'),
	(16, 'Paso Aguerre'),
	(16, 'Picún Leufú'),
	(16, 'Piedra del Aguila'),
	(16, 'Pilo Lil'),
	(16, 'Plaza Huincul'),
	(16, 'Plottier'),
	(16, 'Quili Malal'),
	(16, 'Ramón Castro'),
	(16, 'Rincón de Los Sauces'),
	(16, 'San Martín de Los Andes'),
	(16, 'San Patricio del Chañar'),
	(16, 'Santo Tomás'),
	(16, 'Sauzal Bonito'),
	(16, 'Senillosa'),
	(16, 'Taquimilán'),
	(16, 'Tricao Malal'),
	(16, 'Varvarco'),
	(16, 'Villa Curí Leuvu'),
	(16, 'Villa del Nahueve'),
	(16, 'Villa del Puente Picún Leuvú'),
	(16, 'Villa El Chocón'),
	(16, 'Villa La Angostura'),
	(16, 'Villa Pehuenia'),
	(16, 'Villa Traful'),
	(16, 'Vista Alegre'),
	(16, 'Zapala'),
	(17, 'Aguada Cecilio'),
	(17, 'Aguada de Guerra'),
	(17, 'Allén'),
	(17, 'Arroyo de La Ventana'),
	(17, 'Arroyo Los Berros'),
	(17, 'Bariloche'),
	(17, 'Calte. Cordero'),
	(17, 'Campo Grande'),
	(17, 'Catriel'),
	(17, 'Cerro Policía'),
	(17, 'Cervantes'),
	(17, 'Chelforo'),
	(17, 'Chimpay'),
	(17, 'Chinchinales'),
	(17, 'Chipauquil'),
	(17, 'Choele Choel'),
	(17, 'Cinco Saltos'),
	(17, 'Cipolletti'),
	(17, 'Clemente Onelli'),
	(17, 'Colán Conhue'),
	(17, 'Comallo'),
	(17, 'Comicó'),
	(17, 'Cona Niyeu'),
	(17, 'Coronel Belisle'),
	(17, 'Cubanea'),
	(17, 'Darwin'),
	(17, 'Dina Huapi'),
	(17, 'El Bolsón'),
	(17, 'El Caín'),
	(17, 'El Manso'),
	(17, 'Gral. Conesa'),
	(17, 'Gral. Enrique Godoy'),
	(17, 'Gral. Fernandez Oro'),
	(17, 'Gral. Roca'),
	(17, 'Guardia Mitre'),
	(17, 'Ing. Huergo'),
	(17, 'Ing. Jacobacci'),
	(17, 'Laguna Blanca'),
	(17, 'Lamarque'),
	(17, 'Las Grutas'),
	(17, 'Los Menucos'),
	(17, 'Luis Beltrán'),
	(17, 'Mainqué'),
	(17, 'Mamuel Choique'),
	(17, 'Maquinchao'),
	(17, 'Mencué'),
	(17, 'Mtro. Ramos Mexia'),
	(17, 'Nahuel Niyeu'),
	(17, 'Naupa Huen'),
	(17, 'Ñorquinco'),
	(17, 'Ojos de Agua'),
	(17, 'Paso de Agua'),
	(17, 'Paso Flores'),
	(17, 'Peñas Blancas'),
	(17, 'Pichi Mahuida'),
	(17, 'Pilcaniyeu'),
	(17, 'Pomona'),
	(17, 'Prahuaniyeu'),
	(17, 'Rincón Treneta'),
	(17, 'Río Chico'),
	(17, 'Río Colorado'),
	(17, 'Roca'),
	(17, 'San Antonio Oeste'),
	(17, 'San Javier'),
	(17, 'Sierra Colorada'),
	(17, 'Sierra Grande'),
	(17, 'Sierra Pailemán'),
	(17, 'Valcheta'),
	(17, 'Valle Azul'),
	(17, 'Viedma'),
	(17, 'Villa Llanquín'),
	(17, 'Villa Mascardi'),
	(17, 'Villa Regina'),
	(17, 'Yaminué'),
	(18, 'A. Saravia'),
	(18, 'Aguaray'),
	(18, 'Angastaco'),
	(18, 'Animaná'),
	(18, 'Cachi'),
	(18, 'Cafayate'),
	(18, 'Campo Quijano'),
	(18, 'Campo Santo'),
	(18, 'Capital'),
	(18, 'Cerrillos'),
	(18, 'Chicoana'),
	(18, 'Col. Sta. Rosa'),
	(18, 'Coronel Moldes'),
	(18, 'El Bordo'),
	(18, 'El Carril'),
	(18, 'El Galpón'),
	(18, 'El Jardín'),
	(18, 'El Potrero'),
	(18, 'El Quebrachal'),
	(18, 'El Tala'),
	(18, 'Embarcación'),
	(18, 'Gral. Ballivian'),
	(18, 'Gral. Güemes'),
	(18, 'Gral. Mosconi'),
	(18, 'Gral. Pizarro'),
	(18, 'Guachipas'),
	(18, 'Hipólito Yrigoyen'),
	(18, 'Iruyá'),
	(18, 'Isla De Cañas'),
	(18, 'J. V. Gonzalez'),
	(18, 'La Caldera'),
	(18, 'La Candelaria'),
	(18, 'La Merced'),
	(18, 'La Poma'),
	(18, 'La Viña'),
	(18, 'Las Lajitas'),
	(18, 'Los Toldos'),
	(18, 'Metán'),
	(18, 'Molinos'),
	(18, 'Nazareno'),
	(18, 'Orán'),
	(18, 'Payogasta'),
	(18, 'Pichanal'),
	(18, 'Prof. S. Mazza'),
	(18, 'Río Piedras'),
	(18, 'Rivadavia Banda Norte'),
	(18, 'Rivadavia Banda Sur'),
	(18, 'Rosario de La Frontera'),
	(18, 'Rosario de Lerma'),
	(18, 'Saclantás'),
	(18, '18'),
	(18, 'San Antonio'),
	(18, 'San Carlos'),
	(18, 'San José De Metán'),
	(18, 'San Ramón'),
	(18, 'Santa Victoria E.'),
	(18, 'Santa Victoria O.'),
	(18, 'Tartagal'),
	(18, 'Tolar Grande'),
	(18, 'Urundel'),
	(18, 'Vaqueros'),
	(18, 'Villa San Lorenzo'),
	(19, 'Albardón'),
	(19, 'Angaco'),
	(19, 'Calingasta'),
	(19, 'Capital'),
	(19, 'Caucete'),
	(19, 'Chimbas'),
	(19, 'Iglesia'),
	(19, 'Jachal'),
	(19, 'Nueve de Julio'),
	(19, 'Pocito'),
	(19, 'Rawson'),
	(19, 'Rivadavia'),
	(19, '19'),
	(19, 'San Martín'),
	(19, 'Santa Lucía'),
	(19, 'Sarmiento'),
	(19, 'Ullum'),
	(19, 'Valle Fértil'),
	(19, 'Veinticinco de Mayo'),
	(19, 'Zonda'),
	(20, 'Alto Pelado'),
	(20, 'Alto Pencoso'),
	(20, 'Anchorena'),
	(20, 'Arizona'),
	(20, 'Bagual'),
	(20, 'Balde'),
	(20, 'Batavia'),
	(20, 'Beazley'),
	(20, 'Buena Esperanza'),
	(20, 'Candelaria'),
	(20, 'Capital'),
	(20, 'Carolina'),
	(20, 'Carpintería'),
	(20, 'Concarán'),
	(20, 'Cortaderas'),
	(20, 'El Morro'),
	(20, 'El Trapiche'),
	(20, 'El Volcán'),
	(20, 'Fortín El Patria'),
	(20, 'Fortuna'),
	(20, 'Fraga'),
	(20, 'Juan Jorba'),
	(20, 'Juan Llerena'),
	(20, 'Juana Koslay'),
	(20, 'Justo Daract'),
	(20, 'La Calera'),
	(20, 'La Florida'),
	(20, 'La Punilla'),
	(20, 'La Toma'),
	(20, 'Lafinur'),
	(20, 'Las Aguadas'),
	(20, 'Las Chacras'),
	(20, 'Las Lagunas'),
	(20, 'Las Vertientes'),
	(20, 'Lavaisse'),
	(20, 'Leandro N. Alem'),
	(20, 'Los Molles'),
	(20, 'Luján'),
	(20, 'Mercedes'),
	(20, 'Merlo'),
	(20, 'Naschel'),
	(20, 'Navia'),
	(20, 'Nogolí'),
	(20, 'Nueva Galia'),
	(20, 'Papagayos'),
	(20, 'Paso Grande'),
	(20, 'Potrero de Los Funes'),
	(20, 'Quines'),
	(20, 'Renca'),
	(20, 'Saladillo'),
	(20, 'San Francisco'),
	(20, 'San Gerónimo'),
	(20, 'San Martín'),
	(20, 'San Pablo'),
	(20, 'Santa Rosa de Conlara'),
	(20, 'Talita'),
	(20, 'Tilisarao'),
	(20, 'Unión'),
	(20, 'Villa de La Quebrada'),
	(20, 'Villa de Praga'),
	(20, 'Villa del Carmen'),
	(20, 'Villa Gral. Roca'),
	(20, 'Villa Larca'),
	(20, 'Villa Mercedes'),
	(20, 'Zanjitas'),
	(21, 'Calafate'),
	(21, 'Caleta Olivia'),
	(21, 'Cañadón Seco'),
	(21, 'Comandante Piedrabuena'),
	(21, 'El Calafate'),
	(21, 'El Chaltén'),
	(21, 'Gdor. Gregores'),
	(21, 'Hipólito Yrigoyen'),
	(21, 'Jaramillo'),
	(21, 'Koluel Kaike'),
	(21, 'Las Heras'),
	(21, 'Los Antiguos'),
	(21, 'Perito Moreno'),
	(21, 'Pico Truncado'),
	(21, 'Pto. Deseado'),
	(21, 'Pto. San Julián'),
	(21, 'Pto. 21'),
	(21, 'Río Cuarto'),
	(21, 'Río Gallegos'),
	(21, 'Río Turbio'),
	(21, 'Tres Lagos'),
	(21, 'Veintiocho De Noviembre'),
	(22, 'Aarón Castellanos'),
	(22, 'Acebal'),
	(22, 'Aguará Grande'),
	(22, 'Albarellos'),
	(22, 'Alcorta'),
	(22, 'Aldao'),
	(22, 'Alejandra'),
	(22, 'Álvarez'),
	(22, 'Ambrosetti'),
	(22, 'Amenábar'),
	(22, 'Angélica'),
	(22, 'Angeloni'),
	(22, 'Arequito'),
	(22, 'Arminda'),
	(22, 'Armstrong'),
	(22, 'Arocena'),
	(22, 'Arroyo Aguiar'),
	(22, 'Arroyo Ceibal'),
	(22, 'Arroyo Leyes'),
	(22, 'Arroyo Seco'),
	(22, 'Arrufó'),
	(22, 'Arteaga'),
	(22, 'Ataliva'),
	(22, 'Aurelia'),
	(22, 'Avellaneda'),
	(22, 'Barrancas'),
	(22, 'Bauer Y Sigel'),
	(22, 'Bella Italia'),
	(22, 'Berabevú'),
	(22, 'Berna'),
	(22, 'Bernardo de Irigoyen'),
	(22, 'Bigand'),
	(22, 'Bombal'),
	(22, 'Bouquet'),
	(22, 'Bustinza'),
	(22, 'Cabal'),
	(22, 'Cacique Ariacaiquin'),
	(22, 'Cafferata'),
	(22, 'Calchaquí'),
	(22, 'Campo Andino'),
	(22, 'Campo Piaggio'),
	(22, 'Cañada de Gómez'),
	(22, 'Cañada del Ucle'),
	(22, 'Cañada Rica'),
	(22, 'Cañada Rosquín'),
	(22, 'Candioti'),
	(22, 'Capital'),
	(22, 'Capitán Bermúdez'),
	(22, 'Capivara'),
	(22, 'Carcarañá'),
	(22, 'Carlos Pellegrini'),
	(22, 'Carmen'),
	(22, 'Carmen Del Sauce'),
	(22, 'Carreras'),
	(22, 'Carrizales'),
	(22, 'Casalegno'),
	(22, 'Casas'),
	(22, 'Casilda'),
	(22, 'Castelar'),
	(22, 'Castellanos'),
	(22, 'Cayastá'),
	(22, 'Cayastacito'),
	(22, 'Centeno'),
	(22, 'Cepeda'),
	(22, 'Ceres'),
	(22, 'Chabás'),
	(22, 'Chañar Ladeado'),
	(22, 'Chapuy'),
	(22, 'Chovet'),
	(22, 'Christophersen'),
	(22, 'Classon'),
	(22, 'Cnel. Arnold'),
	(22, 'Cnel. Bogado'),
	(22, 'Cnel. Dominguez'),
	(22, 'Cnel. Fraga'),
	(22, 'Col. Aldao'),
	(22, 'Col. Ana'),
	(22, 'Col. Belgrano'),
	(22, 'Col. Bicha'),
	(22, 'Col. Bigand'),
	(22, 'Col. Bossi'),
	(22, 'Col. Cavour'),
	(22, 'Col. Cello'),
	(22, 'Col. Dolores'),
	(22, 'Col. Dos Rosas'),
	(22, 'Col. Durán'),
	(22, 'Col. Iturraspe'),
	(22, 'Col. Margarita'),
	(22, 'Col. Mascias'),
	(22, 'Col. Raquel'),
	(22, 'Col. Rosa'),
	(22, 'Col. San José'),
	(22, 'Constanza'),
	(22, 'Coronda'),
	(22, 'Correa'),
	(22, 'Crispi'),
	(22, 'Cululú'),
	(22, 'Curupayti'),
	(22, 'Desvio Arijón'),
	(22, 'Diaz'),
	(22, 'Diego de Alvear'),
	(22, 'Egusquiza'),
	(22, 'El Arazá'),
	(22, 'El Rabón'),
	(22, 'El Sombrerito'),
	(22, 'El Trébol'),
	(22, 'Elisa'),
	(22, 'Elortondo'),
	(22, 'Emilia'),
	(22, 'Empalme San Carlos'),
	(22, 'Empalme Villa Constitucion'),
	(22, 'Esmeralda'),
	(22, 'Esperanza'),
	(22, 'Estación Alvear'),
	(22, 'Estacion Clucellas'),
	(22, 'Esteban Rams'),
	(22, 'Esther'),
	(22, 'Esustolia'),
	(22, 'Eusebia'),
	(22, 'Felicia'),
	(22, 'Fidela'),
	(22, 'Fighiera'),
	(22, 'Firmat'),
	(22, 'Florencia'),
	(22, 'Fortín Olmos'),
	(22, 'Franck'),
	(22, 'Fray Luis Beltrán'),
	(22, 'Frontera'),
	(22, 'Fuentes'),
	(22, 'Funes'),
	(22, 'Gaboto'),
	(22, 'Galisteo'),
	(22, 'Gálvez'),
	(22, 'Garabalto'),
	(22, 'Garibaldi'),
	(22, 'Gato Colorado'),
	(22, 'Gdor. Crespo'),
	(22, 'Gessler'),
	(22, 'Godoy'),
	(22, 'Golondrina'),
	(22, 'Gral. Gelly'),
	(22, 'Gral. Lagos'),
	(22, 'Granadero Baigorria'),
	(22, 'Gregoria Perez De Denis'),
	(22, 'Grutly'),
	(22, 'Guadalupe N.'),
	(22, 'Gödeken'),
	(22, 'Helvecia'),
	(22, 'Hersilia'),
	(22, 'Hipatía'),
	(22, 'Huanqueros'),
	(22, 'Hugentobler'),
	(22, 'Hughes'),
	(22, 'Humberto 1º'),
	(22, 'Humboldt'),
	(22, 'Ibarlucea'),
	(22, 'Ing. Chanourdie'),
	(22, 'Intiyaco'),
	(22, 'Ituzaingó'),
	(22, 'Jacinto L. Aráuz'),
	(22, 'Josefina'),
	(22, 'Juan B. Molina')
INSERT INTO Localidades (IDProvincia, Descripcion) VALUES	
	(22, 'Juan de Garay'),
	(22, 'Juncal'),
	(22, 'La Brava'),
	(22, 'La Cabral'),
	(22, 'La Camila'),
	(22, 'La Chispa'),
	(22, 'La Clara'),
	(22, 'La Criolla'),
	(22, 'La Gallareta'),
	(22, 'La Lucila'),
	(22, 'La Pelada'),
	(22, 'La Penca'),
	(22, 'La Rubia'),
	(22, 'La Sarita'),
	(22, 'La Vanguardia'),
	(22, 'Labordeboy'),
	(22, 'Laguna Paiva'),
	(22, 'Landeta'),
	(22, 'Lanteri'),
	(22, 'Larrechea'),
	(22, 'Las Avispas'),
	(22, 'Las Bandurrias'),
	(22, 'Las Garzas'),
	(22, 'Las Palmeras'),
	(22, 'Las Parejas'),
	(22, 'Las Petacas'),
	(22, 'Las Rosas'),
	(22, 'Las Toscas'),
	(22, 'Las Tunas'),
	(22, 'Lazzarino'),
	(22, 'Lehmann'),
	(22, 'Llambi Campbell'),
	(22, 'Logroño'),
	(22, 'Loma Alta'),
	(22, 'López'),
	(22, 'Los Amores'),
	(22, 'Los Cardos'),
	(22, 'Los Laureles'),
	(22, 'Los Molinos'),
	(22, 'Los Quirquinchos'),
	(22, 'Lucio V. Lopez'),
	(22, 'Luis Palacios'),
	(22, 'Ma. Juana'),
	(22, 'Ma. Luisa'),
	(22, 'Ma. Susana'),
	(22, 'Ma. Teresa'),
	(22, 'Maciel'),
	(22, 'Maggiolo'),
	(22, 'Malabrigo'),
	(22, 'Marcelino Escalada'),
	(22, 'Margarita'),
	(22, 'Matilde'),
	(22, 'Mauá'),
	(22, 'Máximo Paz'),
	(22, 'Melincué'),
	(22, 'Miguel Torres'),
	(22, 'Moisés Ville'),
	(22, 'Monigotes'),
	(22, 'Monje'),
	(22, 'Monte Obscuridad'),
	(22, 'Monte Vera'),
	(22, 'Montefiore'),
	(22, 'Montes de Oca'),
	(22, 'Murphy'),
	(22, 'Ñanducita'),
	(22, 'Naré'),
	(22, 'Nelson'),
	(22, 'Nicanor E. Molinas'),
	(22, 'Nuevo Torino'),
	(22, 'Oliveros'),
	(22, 'Palacios'),
	(22, 'Pavón'),
	(22, 'Pavón Arriba'),
	(22, 'Pedro Gómez Cello'),
	(22, 'Pérez'),
	(22, 'Peyrano'),
	(22, 'Piamonte'),
	(22, 'Pilar'),
	(22, 'Piñero'),
	(22, 'Plaza Clucellas'),
	(22, 'Portugalete'),
	(22, 'Pozo Borrado'),
	(22, 'Progreso'),
	(22, 'Providencia'),
	(22, 'Pte. Roca'),
	(22, 'Pueblo Andino'),
	(22, 'Pueblo Esther'),
	(22, 'Pueblo Gral. San Martín'),
	(22, 'Pueblo Irigoyen'),
	(22, 'Pueblo Marini'),
	(22, 'Pueblo Muñoz'),
	(22, 'Pueblo Uranga'),
	(22, 'Pujato'),
	(22, 'Pujato N.'),
	(22, 'Rafaela'),
	(22, 'Ramayón'),
	(22, 'Ramona'),
	(22, 'Reconquista'),
	(22, 'Recreo'),
	(22, 'Ricardone'),
	(22, 'Rivadavia'),
	(22, 'Roldán'),
	(22, 'Romang'),
	(22, 'Rosario'),
	(22, 'Rueda'),
	(22, 'Rufino'),
	(22, 'Sa Pereira'),
	(22, 'Saguier'),
	(22, 'Saladero M. Cabal'),
	(22, 'Salto Grande'),
	(22, 'San Agustín'),
	(22, 'San Antonio de Obligado'),
	(22, 'San Bernardo (N.J.)'),
	(22, 'San Bernardo (S.J.)'),
	(22, 'San Carlos Centro'),
	(22, 'San Carlos N.'),
	(22, 'San Carlos S.'),
	(22, 'San Cristóbal'),
	(22, 'San Eduardo'),
	(22, 'San Eugenio'),
	(22, 'San Fabián'),
	(22, 'San Fco. de Santa Fé'),
	(22, 'San Genaro'),
	(22, 'San Genaro N.'),
	(22, 'San Gregorio'),
	(22, 'San Guillermo'),
	(22, 'San Javier'),
	(22, 'San Jerónimo del Sauce'),
	(22, 'San Jerónimo N.'),
	(22, 'San Jerónimo S.'),
	(22, 'San Jorge'),
	(22, 'San José de La Esquina'),
	(22, 'San José del Rincón'),
	(22, 'San Justo'),
	(22, 'San Lorenzo'),
	(22, 'San Mariano'),
	(22, 'San Martín de Las Escobas'),
	(22, 'San Martín N.'),
	(22, 'San Vicente'),
	(22, 'Sancti Spititu'),
	(22, 'Sanford'),
	(22, 'Santo Domingo'),
	(22, 'Santo Tomé'),
	(22, 'Santurce'),
	(22, 'Sargento Cabral'),
	(22, 'Sarmiento'),
	(22, 'Sastre'),
	(22, 'Sauce Viejo'),
	(22, 'Serodino'),
	(22, 'Silva'),
	(22, 'Soldini'),
	(22, 'Soledad'),
	(22, 'Soutomayor'),
	(22, 'Sta. Clara de Buena Vista'),
	(22, 'Sta. Clara de Saguier'),
	(22, 'Sta. Isabel'),
	(22, 'Sta. Margarita'),
	(22, 'Sta. Maria Centro'),
	(22, 'Sta. María N.'),
	(22, 'Sta. Rosa'),
	(22, 'Sta. Teresa'),
	(22, 'Suardi'),
	(22, 'Sunchales'),
	(22, 'Susana'),
	(22, 'Tacuarendí'),
	(22, 'Tacural'),
	(22, 'Tartagal'),
	(22, 'Teodelina'),
	(22, 'Theobald'),
	(22, 'Timbúes'),
	(22, 'Toba'),
	(22, 'Tortugas'),
	(22, 'Tostado'),
	(22, 'Totoras'),
	(22, 'Traill'),
	(22, 'Venado Tuerto'),
	(22, 'Vera'),
	(22, 'Vera y Pintado'),
	(22, 'Videla'),
	(22, 'Vila'),
	(22, 'Villa Amelia'),
	(22, 'Villa Ana'),
	(22, 'Villa Cañas'),
	(22, 'Villa Constitución'),
	(22, 'Villa Eloísa'),
	(22, 'Villa Gdor. Gálvez'),
	(22, 'Villa Guillermina'),
	(22, 'Villa Minetti'),
	(22, 'Villa Mugueta'),
	(22, 'Villa Ocampo'),
	(22, 'Villa San José'),
	(22, 'Villa Saralegui'),
	(22, 'Villa Trinidad'),
	(22, 'Villada'),
	(22, 'Virginia'),
	(22, 'Wheelwright'),
	(22, 'Zavalla'),
	(22, 'Zenón Pereira'),
	(23, 'Añatuya'),
	(23, 'Árraga'),
	(23, 'Bandera'),
	(23, 'Bandera Bajada'),
	(23, 'Beltrán'),
	(23, 'Brea Pozo'),
	(23, 'Campo Gallo'),
	(23, 'Capital'),
	(23, 'Chilca Juliana'),
	(23, 'Choya'),
	(23, 'Clodomira'),
	(23, 'Col. Alpina'),
	(23, 'Col. Dora'),
	(23, 'Col. El Simbolar Robles'),
	(23, 'El Bobadal'),
	(23, 'El Charco'),
	(23, 'El Mojón'),
	(23, 'Estación Atamisqui'),
	(23, 'Estación Simbolar'),
	(23, 'Fernández'),
	(23, 'Fortín Inca'),
	(23, 'Frías'),
	(23, 'Garza'),
	(23, 'Gramilla'),
	(23, 'Guardia Escolta'),
	(23, 'Herrera'),
	(23, 'Icaño'),
	(23, 'Ing. Forres'),
	(23, 'La Banda'),
	(23, 'La Cañada'),
	(23, 'Laprida'),
	(23, 'Lavalle'),
	(23, 'Loreto'),
	(23, 'Los Juríes'),
	(23, 'Los Núñez'),
	(23, 'Los Pirpintos'),
	(23, 'Los Quiroga'),
	(23, 'Los Telares'),
	(23, 'Lugones'),
	(23, 'Malbrán'),
	(23, 'Matara'),
	(23, 'Medellín'),
	(23, 'Monte Quemado'),
	(23, 'Nueva Esperanza'),
	(23, 'Nueva Francia'),
	(23, 'Palo Negro'),
	(23, 'Pampa de Los Guanacos'),
	(23, 'Pinto'),
	(23, 'Pozo Hondo'),
	(23, 'Quimilí'),
	(23, 'Real Sayana'),
	(23, 'Sachayoj'),
	(23, 'San Pedro de Guasayán'),
	(23, 'Selva'),
	(23, 'Sol de Julio'),
	(23, 'Sumampa'),
	(23, 'Suncho Corral'),
	(23, 'Taboada'),
	(23, 'Tapso'),
	(23, 'Termas de Rio Hondo'),
	(23, 'Tintina'),
	(23, 'Tomas Young'),
	(23, 'Vilelas'),
	(23, 'Villa Atamisqui'),
	(23, 'Villa La Punta'),
	(23, 'Villa Ojo de Agua'),
	(23, 'Villa Río Hondo'),
	(23, 'Villa Salavina'),
	(23, 'Villa Unión'),
	(23, 'Vilmer'),
	(23, 'Weisburd'),
	(24, 'Río Grande'),
	(24, 'Tolhuin'),
	(24, 'Ushuaia'),
	(25, 'Acheral'),
	(25, 'Agua Dulce'),
	(25, 'Aguilares'),
	(25, 'Alderetes'),
	(25, 'Alpachiri'),
	(25, 'Alto Verde'),
	(25, 'Amaicha del Valle'),
	(25, 'Amberes'),
	(25, 'Ancajuli'),
	(25, 'Arcadia'),
	(25, 'Atahona'),
	(25, 'Banda del Río Sali'),
	(25, 'Bella Vista'),
	(25, 'Buena Vista'),
	(25, 'Burruyacú'),
	(25, 'Capitán Cáceres'),
	(25, 'Cevil Redondo'),
	(25, 'Choromoro'),
	(25, 'Ciudacita'),
	(25, 'Colalao del Valle'),
	(25, 'Colombres'),
	(25, 'Concepción'),
	(25, 'Delfín Gallo'),
	(25, 'El Bracho'),
	(25, 'El Cadillal'),
	(25, 'El Cercado'),
	(25, 'El Chañar'),
	(25, 'El Manantial'),
	(25, 'El Mojón'),
	(25, 'El Mollar'),
	(25, 'El Naranjito'),
	(25, 'El Naranjo'),
	(25, 'El Polear'),
	(25, 'El Puestito'),
	(25, 'El Sacrificio'),
	(25, 'El Timbó'),
	(25, 'Escaba'),
	(25, 'Esquina'),
	(25, 'Estación Aráoz'),
	(25, 'Famaillá'),
	(25, 'Gastone'),
	(25, 'Gdor. Garmendia'),
	(25, 'Gdor. Piedrabuena'),
	(25, 'Graneros'),
	(25, 'Huasa Pampa'),
	(25, 'J. B. Alberdi'),
	(25, 'La Cocha'),
	(25, 'La Esperanza'),
	(25, 'La Florida'),
	(25, 'La Ramada'),
	(25, 'La Trinidad'),
	(25, 'Lamadrid'),
	(25, 'Las Cejas'),
	(25, 'Las Talas'),
	(25, 'Las Talitas'),
	(25, 'Los Bulacio'),
	(25, 'Los Gómez'),
	(25, 'Los Nogales'),
	(25, 'Los Pereyra'),
	(25, 'Los Pérez'),
	(25, 'Los Puestos'),
	(25, 'Los Ralos'),
	(25, 'Los Sarmientos'),
	(25, 'Los Sosa'),
	(25, 'Lules'),
	(25, 'M. García Fernández'),
	(25, 'Manuela Pedraza'),
	(25, 'Medinas'),
	(25, 'Monte Bello'),
	(25, 'Monteagudo'),
	(25, 'Monteros'),
	(25, 'Padre Monti'),
	(25, 'Pampa Mayo'),
	(25, 'Quilmes'),
	(25, 'Raco'),
	(25, 'Ranchillos'),
	(25, 'Río Chico'),
	(25, 'Río Colorado'),
	(25, 'Río Seco'),
	(25, 'Rumi Punco'),
	(25, 'San Andrés'),
	(25, 'San Felipe'),
	(25, 'San Ignacio'),
	(25, 'San Javier'),
	(25, 'San José'),
	(25, 'San Miguel de 25'),
	(25, 'San Pedro'),
	(25, 'San Pedro de Colalao'),
	(25, 'Santa Rosa de Leales'),
	(25, 'Sgto. Moya'),
	(25, 'Siete de Abril'),
	(25, 'Simoca'),
	(25, 'Soldado Maldonado'),
	(25, 'Sta. Ana'),
	(25, 'Sta. Cruz'),
	(25, 'Sta. Lucía'),
	(25, 'Taco Ralo'),
	(25, 'Tafí del Valle'),
	(25, 'Tafí Viejo'),
	(25, 'Tapia'),
	(25, 'Teniente Berdina'),
	(25, 'Trancas'),
	(25, 'Villa Belgrano'),
	(25, 'Villa Benjamín Araoz'),
	(25, 'Villa Chiligasta'),
	(25, 'Villa de Leales'),
	(25, 'Villa Quinteros'),
	(25, 'Yánima'),
	(25, 'Yerba Buena'),
	(25, 'Yerba Buena (S)'),
	(26, 'Boston'),
	(27, 'Austin'),
	(28, 'Chicago'),
	(29, 'Leeds'),
	(30, 'Florencia'),
	(31, 'Palermo'),
	(32, 'Roma'),
	(33, 'Montevideo'),
	(27, 'Dallas'),
	(34, 'Detroit'),	
	(35, 'Seattle'),
	(36, 'Reading'),
	(37, 'Napoles')

GO
INSERT INTO TipoClientes(Descripcion) VALUES('Cliente muy importante')
INSERT INTO TipoClientes(Descripcion) VALUES('Educativo público')
INSERT INTO TipoClientes(Descripcion) VALUES('Extranjero')
INSERT INTO TipoClientes(Descripcion) VALUES('Nacional')
INSERT INTO TipoClientes(Descripcion) VALUES('Sin fines de lucro')
INSERT INTO TipoClientes(Descripcion) VALUES('Unicornio')

GO
INSERT INTO Clientes (RazonSocial, IDTipoCliente, Cuit, Email, TelefonoFijo, TelefonoMovil, IDLocalidad) VALUES ('Brian Lara', 1, '11-111111-1', 'hola@brianlara.com.ar', '45656643', '1128473829', 2391)
INSERT INTO Clientes (RazonSocial, IDTipoCliente, Cuit, Email, TelefonoFijo, TelefonoMovil, IDLocalidad) VALUES ('Legna Nomis', 6, '44-44444-4', 'hola@legnanomis.com.ar', NULL, NULL, 2394)
INSERT INTO Clientes (RazonSocial, IDTipoCliente, Cuit, Email, TelefonoFijo, TelefonoMovil, IDLocalidad) VALUES ('Kloster Inc', 3, '99', NULL, '(49) 08363362115', NULL, 2395)
INSERT INTO Clientes (RazonSocial, IDTipoCliente, Cuit, Email, TelefonoFijo, TelefonoMovil, IDLocalidad) VALUES ('UTN', 2, '22-222222-2', 'info@utn.edu.ar', '11456567', NULL, 249)
INSERT INTO Clientes (RazonSocial, IDTipoCliente, Cuit, Email, TelefonoFijo, TelefonoMovil, IDLocalidad) VALUES ('World Animal Protection', 5, '98', 'wap@wap.org', '44233423', NULL, 2392)
INSERT INTO Clientes (RazonSocial, IDTipoCliente, Cuit, Email, TelefonoFijo, TelefonoMovil, IDLocalidad) VALUES ('Clifton Goldney Inc', 3, '33-333333-3', 'clifton@goldney.com.ar', NULL, NULL, 2393)
INSERT INTO Clientes (RazonSocial, IDTipoCliente, Cuit, Email, TelefonoFijo, TelefonoMovil, IDLocalidad) VALUES ('Strebern Ich', 3, '55-555555-5', NULL, NULL, NULL, 2387)
INSERT INTO Clientes (RazonSocial, IDTipoCliente, Cuit, Email, TelefonoFijo, TelefonoMovil, IDLocalidad) VALUES ('Vaca SA', 4, '66-666666-6', 'info@alancow.com.ar', NULL, '1147483934', 287)
INSERT INTO Clientes (RazonSocial, IDTipoCliente, Cuit, Email, TelefonoFijo, TelefonoMovil, IDLocalidad) VALUES ('Hugo Gomez', 6, '77-777777-7', 'hola@hugo.com.ar', NULL, NULL, 287)
INSERT INTO Clientes (RazonSocial, IDTipoCliente, Cuit, Email, TelefonoFijo, TelefonoMovil, IDLocalidad) VALUES ('Adducci', 4, '88-888888-8', 'adducci@gmail.com', '114838992', '1148383438', NULL)
INSERT INTO Clientes (RazonSocial, IDTipoCliente, Cuit, Email, TelefonoFijo, TelefonoMovil, IDLocalidad) VALUES ('Estudio Contable Arevalo y Cía', 4, '99-999999-9', 'arevalo@yahoo.com.ar', '114838385', NULL, 429)
INSERT INTO Clientes (RazonSocial, IDTipoCliente, Cuit, Email, TelefonoFijo, TelefonoMovil, IDLocalidad) VALUES ('White SA', 4, '11-0000000-1', 'nazarenwhite@hotmail.com', NULL, NULL, 1166)

GO
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('A100', 'Scholar', 'Aplicación que permitirá gestionar tu establecimiento educativo', 400000, '2020-5-14', NULL, 1, 1)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('B125', 'Mailer', 'Servicio de envío de mail masivo.', 125000, '2019-7-21', NULL, 2, 1)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('CC45', 'Sales manager', 'Gestor de ventas.', 800000, '2019-12-8', NULL, 1, 1)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('CC46', 'Seals manager', 'Gestor de focas.', 950000, '2020-3-13', NULL, 5, 1)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('A120', 'Monkey Doctor', 'Juego muy popular de preguntas y respuestas', 1000000, '2014-11-4', '2015-12-10', 1, 0)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('A113', 'Goto Game Jam Winner Randomizer', NULL, 50000, '2020-12-12', '2020-12-20', 1, 0)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('B99', 'UTN Bot', 'Un corrector de exámenes para LAB1, LAB2 y LAB3', 450000, '2020-3-11', NULL, 2, 1)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('B100', 'PetApp', 'Aplicación que permite encontrar adoptantes a mascotas abandonadas', 100000, '2018-10-10', '2019-4-15', 5, 0)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('D134', 'GetApp', 'Aplicación móvil tipo Alarma que te despierta o llama a la policía', 400000, '2021-5-25', NULL, 1, 1)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('E1444', 'Wine', 'Emulador de aplicaciones de Windows en Linux', 5450000, '2005-5-8', NULL, 10, 1)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('F45', 'PlagiApp', 'Aplicación que compara exámenes y te sugiere cuales sospechosamente parecidos.', 675000, '2018-5-14', NULL, 2, 1)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('Z111', 'Zoomba', 'Clases de baile online', 450000, '2021-9-30', NULL, 8, 1)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('C40', 'Faker', 'Aplicación para inventar datos en las bases de datos', 50000, '2000-12-31', '2001-2-5', 2, 0)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('A33', 'Moodler', 'Gestor de Campus Virtual Moodle', 120500, '2000-3-15', '2000-3-30', 4, 0)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('D33', 'Gentesss', NULL, 140000, '2021-6-27', NULL, 3, 1)
INSERT INTO Proyectos(ID, Nombre, Descripcion, Costo, FechaInicio, FechaFin, IDCliente, Estado) VALUES('F23', 'ColourAdvisor', 'Aplicación que recomienda paletas de colores para tu aplicación', 78000, '2020-6-13', '2020-6-25', 9, 0)

GO
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('A100', 'Login', 'Login de usuarios', 111, 100000, '2020-9-1', '2020-5-18', '2020-5-22')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('A100', 'Staff', 'Docentes y no docentes', 170, 200000, '2020-6-16', '2020-5-22', '2020-10-13')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('A100', 'Estudiantes', 'Estudiantes del sistema', 125, 200000, '2020-7-2', '2020-5-15', '2020-9-1')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('A100', 'Calificaciones', 'Calificaciones de estudiantes', 155, 400000, '2020-7-11', '2020-5-18', '2020-9-13')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('A100', 'Pagos', 'Pagos de cuotas', 65, 80000, '2020-7-31', '2020-5-23', '2020-9-11')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Sistema de mail', 'Sistema de mail', 88, 20000, '2019-1-2', '2018-10-19', '2018-12-22')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Proveedores', 'Subsistema de proveedores', 111, 50000, '2018-11-20', '2018-10-11', '2019-2-3')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Pagos', 'Subsistema de pagos', 158, 25000, '2019-1-27', '2018-10-20', '2019-1-22')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Clientes', 'Subsistema de clientes', 153, 50000, '2018-12-17', '2018-10-11', '2019-2-14')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Productos', 'Subsistema de productos', 112, 50000, '2018-12-3', '2018-10-13', '2018-11-21')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Ventas', 'Subsistema de ventas', 53, 25000, '2019-1-12', '2018-10-14', '2019-3-2')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Animales', 'Registro de animales de la organización', 67, 20000, '2018-11-15', '2018-10-11', '2018-11-19')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Stock de comida', 'Registro de alimento de los animales', 64, 20000, '2018-12-15', '2018-10-15', '2019-1-18')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Stock de vacunas', 'Registro de vacunas', 144, 33333.33, '2019-1-3', '2018-10-17', '2019-1-3')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('A100', 'Mecánicas', 'Mecánicas del juego', 86, 200000, '2020-8-21', '2020-5-15', '2020-8-16')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('A100', 'Sistema', 'Módulo general de la aplicación', 88, 80000, '2020-6-19', '2020-5-21', '2020-9-10')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Corrector', 'Módulo general de la aplicación', 99, 25000, '2019-1-21', '2018-10-12', '2019-1-11')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Adoptantes', 'Módulo que registra información completa de los adoptantes', 132, 25000, '2018-11-30', '2018-10-18', '2019-3-8')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Mascotas', 'Módulo que registra informción de las mascotas', 111, 100000, '2019-1-31', '2018-10-17', '2018-12-14')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Adopciones', 'Módulo que registra adopciones', 84, 33333.33, '2019-1-17', '2018-10-19', '2018-12-24')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Monetización', 'Módulo de publicidad', 166, 50000, '2018-12-24', '2018-10-17', '2018-11-29')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('D134', 'Sistema', 'Sistema de alarma', 81, 133333.33, NULL, NULL, NULL)
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('D134', 'Monetización', 'Módulo de publicidad y monetización', 58, 133333.33, NULL, NULL, NULL)
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('E1444', 'Sistema', 'Sistema general del emulador', 172, 2725000, '2005-7-20', '2005-5-18', '2005-7-17')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('E1444', 'Reportes de fallos', 'Módulo de reportes de fallos', 107, 2725000, '2005-6-23', '2005-5-13', '2005-5-26')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('E1444', 'Log', 'Módulo de registro de errores', 74, 1362500, '2005-8-29', '2005-5-14', '2005-6-11')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('F45', 'Sistema', 'Sistema general del detector de plagios', 155, 337500, '2018-8-17', '2018-5-18', '2018-10-15')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('F45', 'Reportes de fallos', 'Módulo de reportes de fallos', 131, 168750, '2018-6-7', '2018-5-24', '2018-10-7')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('F23', 'Login', 'Login de usuarios', 100, 15600, '2020-8-9', '2020-6-23', '2020-11-1')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('F23', 'Instructores', 'Registro de instructores', 114, 39000, '2020-9-6', '2020-6-18', '2020-10-8')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('F23', 'Clases', 'Streaming de clases', 165, 78000, '2020-8-26', '2020-6-18', '2020-8-24')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('B100', 'Faker', 'Generador de datos al azar', 134, 33333.33, '2019-2-1', '2018-10-19', '2018-10-21')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('A100', 'Acceso', 'Acesso al sistema', 98, 133333.33, '2020-8-6', '2020-5-18', '2020-9-22')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('A100', 'Cursos', 'Módulo de cursos y actividades', 171, 80000, '2020-6-21', '2020-5-17', '2020-6-1')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('A100', 'Usuarios', 'Módulo de usuarios y permisos', 109, 100000, '2020-7-23', '2020-5-19', '2020-10-13')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('A100', 'Calificaciones', 'Módulo de calificaciones', 115, 200000, '2020-6-15', '2020-5-22', '2020-8-21')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('D134', 'Sistema', 'Sistema general', 54, 133333.33, NULL, NULL, NULL)
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('E1444', 'Colorizr', 'Sistema recomendador de colores', 107, 2725000, '2005-7-4', '2005-5-14', '2005-10-9')
INSERT INTO Modulos(IDProyecto, Nombre, Descripcion, TiempoEstimado, CostoEstimado, FechaFinEstimada, FechaRealInicio, FechaRealFin) VALUES ('E1444', 'Daltonic', 'Subsistema que evita paletas no recomendadas para gente con daltonismo', 47, 1362500, '2005-7-12', '2005-5-13', '2005-10-9')

GO
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Achaval Duria', 'Joaquin', NULL, '(387) 962-2847', '1968-5-3', 'Obispo Lagorio 3548', 587, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Alpuin Schunk', 'Leonardo Ezequiel', 'lalpuin@notmyrealmail.com', NULL, '1993-1-31', 'Teniente De Amos 1067', 587, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Arostegui', 'Isidoro', 'iarostegui@nasa.gov', '(695) 920-0076', '1999-1-12', 'Virrey Kloster 9440', 249, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Ayala', 'Elizabeth Carolina', 'eayala@google.com', NULL, '1972-8-28', NULL, NULL, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Badano', 'Alejandro Agustin', NULL, '(357) 874-7957', '1996-10-25', 'Doctor Carrasquero 8513', 1166, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Barrios', 'Paola Elizabeth', 'pneighborhood@me.dev', '(946) 907-8987', '1988-12-22', 'Doctora Alberti 2622', 287, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Crucci', 'Lucas', 'lcrucci@hotmail.com.pe', '(389) 615-9729', '1966-6-4', 'Presidente Carrasquero 9910', 587, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Del Pino', 'Emiliano', 'efromthepine@notmyrealmail.com', '(368) 886-5181', '1977-12-31', 'Villa Laurentino Goncalves 48', 2387, 'E')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Di Fulvio', 'Federico Damian', 'fdifulvio@gmail.com', NULL, '1978-6-9', 'Doctora Fahler 2288', 1166, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Fahler', 'Matias Andres', NULL, '(186) 828-6592', '1985-4-24', 'Virrey Gazzo 2281', 2388, 'E')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Ferrante', 'Bruno Alexis', 'bferrante@hotmail.com.pe', '(926) 973-5945', '1981-8-21', 'Cabo Dirube 828', 429, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Figueira', 'Alexis Damian', 'afigueira@hotmail.com.uy', NULL, '1994-4-22', 'Cabo Laino 9194', 2389, 'E')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Galarza', 'Cecilia Verónica', 'cgalarza@utn.edu.ar', NULL, '1989-2-7', 'General Alberti 7067', 249, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Gazzo', 'Alejandro Matias', 'agazzo@notmyrealmail.com', NULL, '1990-3-12', 'Brigadier Barrios 8517', 287, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Godoy', 'Nahuel Alejandro', 'ngodoy@google.com', NULL, '1971-12-28', 'Brigadier Clifton Goldney 9023', 287, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Gonzalez', 'Edgardo Simon', 'egonzalez@fakemail.com', NULL, '1967-1-2', NULL, NULL, 'E')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Ibazeta', 'Pablo Agustín', 'pibazeta@google.com', '(578) 581-0349', '1982-7-1', 'Doctora Galarza 4188', 249, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Larroca', 'Javier Agustin', 'jlarroca@hotmail.com.ar', '(723) 346-3332', '1983-11-3', 'Virrey Martinez 1648', 2390, 'E')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Laurentino Goncalves', 'Yesica Regina', 'ylaurentino@independiente.com', '(101) 716-0947', '1997-4-15', 'Cabo Flori 1649', 1166, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Mar Cardozo', 'Zair Andres', 'zmar@hotmail.com.uy', '(203) 991-1918', '1971-9-19', 'Cabo Crucci 986', 2383, 'E')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Martinez', 'Jonathan Daniel', NULL, '(328) 853-6797', '1973-7-25', 'Presidente Simon 5842', 587, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Mena', 'German Emanuel', NULL, '(859) 564-9626', '1984-9-1', 'General Clifton Goldney 474', 249, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Miranda', 'Maximiliano Guillermo', 'mmiranda@hotmail.com.ar', '(346) 791-8453', '1979-7-7', 'Virrey Barreto Hernandez 310', 1166, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Molteni', 'Bruno Mauricio', 'bmolteni@hotmail.com.uy', NULL, '1974-11-2', 'General Ayala 6956', 287, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Petrignani Castro', 'Ignacio', 'ipetrignani@notmyrealmail.com', '(558) 813-4402', '1989-2-6', NULL, NULL, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Plaza', 'Valentin', 'vplaza@notmyrealmail.com', '(779) 742-0557', '1966-8-3', 'Obispo Dominguez 9081', 2384, 'E')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Popp', 'Alexander Alberto', 'apopp@google.com', '(488) 244-5467', '1994-8-24', 'Villa Blanco 8985', 249, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Quintana Soria', 'Matias Joel', 'mquintana@hotmail.com.pe', '(669) 213-0345', '1989-1-31', 'Presidente Ciccarelli 8343', 1518, 'E')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Rasjido', 'Adriel Elian', 'arasjido@frgp.utn.edu.ar', NULL, '1998-4-27', 'Teniente Lara 1971', 2386, 'E')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Robles', 'Agustin Lautaro', 'arobles@hotmail.com.ar', '(970) 885-0929', '1972-1-30', NULL, NULL, 'E')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Sanchez Villar', 'Matias', 'msanchez@fakemail.com', '(533) 285-8591', '1971-2-20', 'Doctor Barea 721', 2385, 'E')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Scalesi', 'Leonardo Martin', NULL, '(806) 630-4551', '1999-5-3', 'Virrey Ciccarelli 2899', 429, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Scutti', 'Tomas', 'tscutti@notmyrealmail.com', '(169) 249-0460', '1994-12-6', 'Virrey Lagorio 40', 249, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Stamm', 'Walter Emmanuel', 'wstamm@argentina.ar', NULL, '1971-11-16', NULL, NULL, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Tejeda', 'Mathias Leandro', 'mtejeda@hotmail.com', '(963) 306-5247', '1987-7-11', 'Doctora Barrios 1948', 429, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Trunso', 'Daniel Alejandro', NULL, '(977) 335-7032', '1971-9-18', 'Cabo Figueira 3473', 1166, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Vasquez Quispe', 'Elmer Dennis', NULL, '(324) 635-0486', '1975-6-18', NULL, NULL, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Vigliaccio', 'Sofia Noemi', 'svigliaccio@frgp.utn.edu.ar', '(564) 377-2363', '1969-10-22', 'General Lagorio 5572', 587, 'I')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Virasoro', 'Alejandro', 'avirasoro@hotmail.com.ar', NULL, '1987-2-13', 'Doctor Fahler 1936', 2385, 'E')
INSERT INTO Colaboradores(Apellidos, Nombres, Email, TelefonoMovil, FechaNacimiento, Direccion, IDLocalidad, TipoColaborador) VALUES ('Yomayel', 'Luciano Federico', 'lyomayel@hotmail.com', '(625) 229-4746', '1992-3-21', 'General Brizzi 6443', 249, 'I')

